// kings-poland.js — Królowie Polski / Kings of Poland
// Dynasties: Piast · Anjou · Jagiellonian · Elected Kings (1573–1795)

window.ELIADORA_DATA = {
  familyName: "Polskich Królów",
  defaultFocus: "kazimierz3",
  music: "music/background.mp3",
  portraitFolder: "Matejko_Stroynowski_Papieski",
  succession: [
    "mieszko1","boleslaw1","mieszko2","bezprym","kazimierz1","boleslaw2",
    "wladyslaw1h","boleslaw3","boleslaw4","mieszko3","kazimierz2","leszek1",
    "henryk1b","henryk2p","boleslaw5","leszek2","przemysl2","wladyslaw1l",
    "kazimierz3","ludwik1","jadwiga","wladyslaw2j","wladyslaw3","kazimierz4",
    "jan1","aleksander1","zygmunt1","zygmunt2","henryk_walois","anna_jag",
    "stefan_batory","zygmunt3","wladyslaw4","jan2","michal_wisnow",
    "jan3_sobieski","august2","stanislaw_lesz","august3","stanislaw_aug"
  ],
  people: [

    // ═══════════════════════════════════════════════════════════════
    // PIAST DYNASTY  (~960–1370)
    // ═══════════════════════════════════════════════════════════════

    { id:"mieszko1", fn:"Mieszko I", ln:"Piast", g:"M", b:"935", d:"992", rs:"~960", re:"992",
      bp:"Polska", dp:"Poznań, Polska", nat:"PL", p:[], s:["oda_haldensleben","dobrawa"], image:"Matejko_Stroynowski_Papieski/mieszko_i.jpg", map:"maps/960-992.png", media:"video/mieszko.mp4",
      bio:{ pl:"Książę i założyciel państwa polskiego.\n\nNajważniejsze daty: 966 — chrzest Polski, wejście do łacińskiego świata; 972 — bitwa pod Cedynią, pierwsza poświadczona polsko-niemiecka bitwa, wygrana; ok. 991 — akt Dagome iudex, oddający Polskę pod opiekę papieską — najstarszy zachowany dokument polskiej państwowości.\n\nMiał dwie żony: Dobrawę Przemyślidkę (zm. 977), przez którą Polska weszła w orbitę chrześcijańskiej Europy, i Odę z Haldensleben, córkę saskiego margrabiego. Miał co najmniej czworo dzieci: Bolesława Chrobrego i Świętosławę (przyszłą królową Szwecji i Danii, matkę Knuta Wielkiego) z Dobrawą; Lamberta i Świętopełka z Odą.\n\nChrzest w 966 roku był jego mistrzowskim posunięciem politycznym — nie religijnym. Rządził bez papieskiego błogosławieństwa, bez uznania cesarza, bez miejsca w łacińskim świecie. Jedna decyzja zmieniła wszystko: zrobiła z niego legalnego władcę przez noc i odebrała wrogom pretekst do zniszczenia go jako poganina. Zbudował nie tylko państwo, ale i trwałe roszczenie do niego.\n\nUmarł 25 maja 992 roku w Poznaniu. Pochowany w katedrze poznańskiej.", en:"Duke and founder of the Polish state.\n\nKey dates: 966 — the Baptism of Poland, entry into the Latin world; 972 — the Battle of Cedynia, the first documented Polish-German battle, won; c. 991 — the Dagome iudex act, placing Poland under papal protection, the oldest surviving document of Polish statehood.\n\nHe had two wives: Dobrawa of Bohemia (d. 977), through whom Poland entered the orbit of Christian Europe, and Oda of Haldensleben, daughter of a Saxon margrave. He had at least four children: Bolesław Chrobry and Świętosława — future queen of Sweden and Denmark, mother of Cnut the Great — with Dobrawa; Lambert and Świętopełk with Oda.\n\nThe baptism of 966 was his political masterstroke — not a religious one. He ruled without papal blessing, without imperial recognition, without a place in the Latin world. One decision changed everything: it made him a legitimate ruler overnight and stripped his enemies of the pagan pretext for destroying him. He built not just a state but a permanent claim to one.\n\nHe died on 25 May 992 in Poznań and is buried in Poznań Cathedral." }},

    { id:"dobrawa", fn:"Dobrawa", ln:"Przemyślidów", g:"F", b:"940", d:"977",
      bp:"Bohemia", dp:"Polska", nat:"CZ", p:[], s:["mieszko1"], image:"Matejko_Stroynowski_Papieski/dobrawa_przemyslidka.jpg",
      bio:{ pl:"Czeska księżniczka i katalizator najważniejszej decyzji w historii polskiej państwowości.\n\nNajważniejsze daty: ok. 965 — przybycie do Polski i ślub z Mieszkiem I; 966 — chrzest Mieszka I, wejście Polski w krąg chrześcijańskiej Europy; 977 — śmierć Dobrawy w Polsce.\n\nMiała jednego męża — Mieszka I — i co najmniej dwoje dzieci: syna Bolesława Chrobrego, przyszłego pierwszego króla Polski, oraz córkę Świętosławę, przyszłą królową Szwecji i Danii.\n\nPrzyszła z Czech niosąc wiarę, której mąż jeszcze nie podzielał. Kroniki przypisują jej ogromny wpływ na nawrócenie Mieszka — czy go przekonała, czy jedynie dostarczyła politycznego pretekstu, nigdy się nie dowiemy. Jedna kobieta, jedno małżeństwo, jedna decyzja — i Polska stała się innym państwem.\n\nUmarła około 977 roku w Polsce. Przyczyna śmierci nieznana.", en:"A Bohemian princess and the catalyst behind the most consequential decision in early Polish history.\n\nKey dates: c. 965 — arrival in Poland and marriage to Mieszko I; 966 — Baptism of Poland, the country's entry into Christian Europe; 977 — Dobrawa's death in Poland.\n\nShe had one husband — Mieszko I — and at least two children: her son Bolesław Chrobry, the future first King of Poland, and her daughter Świętosława, future queen of Sweden and Denmark.\n\nShe came from Bohemia bearing a faith her husband did not yet share. The chronicles give her enormous credit for Mieszko's conversion — whether she persuaded him or merely provided the political pretext, we will never know. One woman, one marriage, one decision — and Poland became a different country.\n\nShe died around 977 in Poland. Cause of death unknown." }},

    { id:"oda_haldensleben", fn:"Oda", ln:"z Haldensleben", g:"F", b:"~955", d:"1023",
      bp:"Haldensleben, Saksonia", dp:"Niemcy", nat:"DE", p:[], s:["mieszko1"], image:null,
      bio:{ pl:"Saska arystokratka i druga żona Mieszka I — polityczne zabezpieczenie zachodniej granicy młodego państwa polskiego.\n\nNajważniejsze daty: ok. 979 — ślub z Mieszkiem I po śmierci Dobrawy; 992 — śmierć Mieszka I i ucieczka Ody z synami na czeski dwór; 1023 — śmierć Ody w Niemczech.\n\nMiała jednego męża — Mieszka I — i co najmniej dwóch synów: Lamberta i Świętopełka. Obaj, traktowani przez Bolesława Chrobrego jako zagrożenie dla tronu, zostali wygnani razem z matką natychmiast po śmierci ojca.\n\nCórka margrabiego Dytryka z Marchii Północnej — jej ślub z Mieszkiem dał polskiemu władcy saską żonę i zachodnie zaplecze polityczne w chwili, gdy cesarstwo było największym zagrożeniem. Gdy Mieszko umarł, ten układ runął w ciągu dni. Bolesław objął władzę jako jedyny dziedzic, a Oda z synami musiała szukać schronienia na czeskim dworze.\n\nPrzeżyła Mieszka o ponad trzydzieści lat. Umarła w Niemczech w 1023 roku. Przyczyna śmierci nieznana.", en:"A Saxon aristocrat and Mieszko I's second wife — the political anchor on the western frontier of the young Polish state.\n\nKey dates: c. 979 — marriage to Mieszko I after Dobrawa's death; 992 — Mieszko's death and Oda's flight with her sons to the Bohemian court; 1023 — Oda's death in Germany.\n\nShe had one husband — Mieszko I — and at least two sons: Lambert and Świętopełk. Both, seen by Bolesław Chrobry as rival claimants, were expelled from Poland alongside their mother immediately after their father's death.\n\nDaughter of Margrave Dietrich of the Northern March — her marriage to Mieszko gave the Polish ruler a high-born Saxon wife and political backing on the western frontier at the moment when the empire was the greatest threat. When Mieszko died, that arrangement collapsed within days. Bolesław took power alone, and Oda and her sons had to seek refuge at the Bohemian court.\n\nShe outlived Mieszko by more than thirty years. She died in Germany in 1023. Cause of death unknown." }},

    { id:"swietoslawa_piastowna", fn:"Świętosława", ln:"Piastówna", g:"F", b:"~965", d:"~1014",
      bp:"Polska", dp:"Dania", nat:"PL", p:["mieszko1"], s:[], image:null,
      bio:{ pl:"Córka Mieszka I, dwukrotna królowa Skandynawii i matka jednych z najpotężniejszych władców Europy Północnej.\n\nNajważniejsze daty: ok. 984 — ślub z Erykiem Zwycięskim, królem Szwecji; ok. 995 — śmierć Eryka i ponowne małżeństwo ze Swenem Widłobrodym, królem Danii; 1000 — Swen podbija całą Skandynawię; ok. 1014 — śmierć Świętosławy.\n\nMiała dwóch mężów: Eryka Zwycięskiego, króla Szwecji — z nim miała syna Olafa Skötkonunga, pierwszego chrześcijańskiego króla Szwecji — i Swena Widłobrodego, króla Danii, z którym miała syna Knuta Wielkiego.\n\nSagi nordyckie pamiętają ją jako Sygrydę Dumną — kobietę, która odrzuciła kilku zalotników jako niegodnych jej ręki i podobno kazała spalić jednego z nich żywcem na uczcie. Identyfikacja z córką Mieszka jest głęboko zakorzeniona w tradycji historycznej, choć historiograficznie niepewna. Pewne jest to, że jej syn Knut Wielki rządził jednocześnie Anglią, Danią i Norwegią. Jeśli tradycja jest trafna, żadna inna córka Piastów nie odcisnęła głębszego piętna na historii Europy Północnej.\n\nUmarła ok. 1014 roku, prawdopodobnie w Danii lub Anglii. Przyczyna śmierci nieznana.", en:"Daughter of Mieszko I, twice queen of Scandinavia, and mother of some of the most powerful rulers of Northern Europe.\n\nKey dates: c. 984 — marriage to Eric the Victorious, King of Sweden; c. 995 — Eric's death and remarriage to Sweyn Forkbeard, King of Denmark; 1000 — Sweyn conquers all Scandinavia; c. 1014 — Świętosława's death.\n\nShe had two husbands: Eric the Victorious of Sweden, with whom she had her son Olof Skötkonung — the first Christian king of Sweden — and Sweyn Forkbeard of Denmark, with whom she had Cnut the Great.\n\nThe Norse sagas remember her as Sigrid the Haughty — the woman who rejected multiple suitors as unworthy of her hand and allegedly had one burned alive at a feast. The identification with Mieszko's daughter is deeply embedded in historical tradition, though not fully confirmed by scholarship. What is certain is that her son Cnut the Great ruled England, Denmark and Norway simultaneously. If the tradition holds, no other Piast daughter left a deeper mark on Northern European history.\n\nShe died around 1014, probably in Denmark or England. Cause of death unknown." }},

    { id:"lambert_piast", fn:"Lambert", ln:"Piast", g:"M", b:"~980", d:"",
      bp:"Polska", dp:"Polska", nat:"PL", p:["mieszko1","oda_haldensleben"], s:[], image:null,
      bio:{ pl:"Syn Mieszka I i Ody z Haldensleben — prawy dziedzic tronu, który stał się niebezpieczny przez sam fakt istnienia.\n\nNajważniejsze daty: ok. 980 — narodziny w Polsce; 992 — śmierć ojca Mieszka I i natychmiastowe wygnanie przez brata Bolesława Chrobrego; po 992 — Lambert znika ze źródeł historycznych.\n\nMiał jedną matkę — Odę z Haldensleben — i jednego brata — Świętopełka, z którym uciekł do Czech w 992 roku. Żadnych udokumentowanych małżeństw ani potomków.\n\nUrodzony z legalnego małżeństwa, Lambert był prawowitym dziedzicem polskiego tronu, który w chwili śmierci ojca stał się głównym zagrożeniem dla Bolesława Chrobrego. Bolesław nie czekał na próbę sił: wygnał Lamberta i Świętopełka z matką, zanim zdążyli zebrać stronników. Historia zachowała ich imiona tylko dlatego, że ich istnienie mogło stanowić zagrożenie — w końcu nim nie było.\n\nData i przyczyna śmierci nieznane. Znika ze źródeł po 992 roku.", en:"Son of Mieszko I and Oda of Haldensleben — a legitimate heir who became dangerous simply by existing.\n\nKey dates: c. 980 — born in Poland; 992 — their father Mieszko I's death and immediate expulsion by half-brother Bolesław Chrobry; after 992 — Lambert vanishes from the historical record.\n\nHe had one mother — Oda of Haldensleben — and one brother — Świętopełk, with whom he fled to Bohemia in 992. No documented marriages or children.\n\nBorn of a legal marriage, Lambert was a legitimate heir to the Polish throne who became Bolesław Chrobry's main rival the moment their father died. Bolesław did not wait for a test of strength: he expelled Lambert and Świętopełk with their mother before they could gather supporters. History preserved their names only because their existence might have been a threat — in the end, it was not.\n\nDate and cause of Lambert's death unknown. He vanishes from the sources after 992." }},

    { id:"swietopelk_piast_i", fn:"Świętopełk", ln:"Piast", g:"M", b:"~982", d:"",
      bp:"Polska", dp:"Polska", nat:"PL", p:["mieszko1","oda_haldensleben"], s:[], image:null,
      bio:{ pl:"Syn Mieszka I i Ody z Haldensleben — młodszy brat Lamberta, razem wykluczony z dziedzictwa po ojcu.\n\nNajważniejsze daty: ok. 982 — narodziny w Polsce; 992 — śmierć ojca i wygnanie z Polski przez Bolesława Chrobrego; po 992 — znika ze źródeł historycznych.\n\nMiał jedną matkę — Odę z Haldensleben — i jednego brata — Lamberta, z którym uciekł z matką do Czech. Żadnych udokumentowanych małżeństw ani potomków.\n\nBrat Lamberta i syn Ody z Haldensleben — razem stanowili żywy dowód, że Bolesław Chrobry nie jest jedynym prawowitym dziedzicem ojca. Bolesław rozwiązał tę zagadkę przez wygnanie, nie przez negocjację. Historia zapamiętała imię Świętopełka wyłącznie dlatego, że jego istnienie mogło stanowić zagrożenie — w końcu nim nie było.\n\nData i przyczyna śmierci nieznane. Znika ze źródeł po 992 roku.", en:"Son of Mieszko I and Oda of Haldensleben — Lambert's younger brother, expelled from their father's inheritance alongside him.\n\nKey dates: c. 982 — born in Poland; 992 — their father's death and expulsion from Poland by Bolesław Chrobry; after 992 — vanishes from the historical record.\n\nHe had one mother — Oda of Haldensleben — and one brother — Lambert, with whom he fled with his mother to Bohemia. No documented marriages or children.\n\nLambert's brother and Oda's son — together they were living proof that Bolesław Chrobry was not the only legitimate heir to their father's duchy. Bolesław resolved that problem through exile, not negotiation. History preserved Świętopełk's name only because his existence might have been a threat — in the end, it was not.\n\nDate and cause of death unknown. He vanishes from the sources after 992." }},

    { id:"boleslaw1", fn:"Bolesław I", ln:"Chrobry", g:"M", b:"967", d:"1025", rs:"992", re:"1025",
      bp:"Polska", dp:"Poznań, Polska", nat:"PL", p:["mieszko1","dobrawa"], s:["nn_misnska","judith_wegierska","emnilda"], image:"Matejko_Stroynowski_Papieski/boleslaw_chrobry.jpg", map:"maps/992-1025.png",
      bio:{ pl:"Pierwszy król Polski, zdobywca, dyplomata i budowniczy polskiej metropolii kościelnej.\n\nNajważniejsze daty: 992 — przejął władzę po ojcu Mieszku I, natychmiast wygnając braci przyrodnich i matkę Odę; 1000 — Zjazd Gnieźnieński: cesarz Otto III uznaje polskie arcybiskupstwo i kładzie własną koronę imperialną na skroni Bolesława; 1002–1018 — długoletnie wojny z Rzeszą o Łużyce i Milsko; 1018 — zdobycie Kijowa, odzyskanie Grodów Czerwieńskich; 1025 — koronacja królewska, pierwsza w historii Polski.\n\nMiał cztery żony: nieznaną z imienia córkę margrabiego Rikdaga z Miśni (ok. 984–987), Judytę Węgierską (ok. 987–992), Emnildę z Łużyc (992–1017) — tę, która liczyła się najbardziej, matkę jego głównych następców — i Odę Miśnieńską (po 1018). Miał co najmniej siedmioro dzieci, w tym Bezpryma, Mieszka II i Ottona z Emnildą oraz Regelindę.\n\nSpędził całe życie na ekspansji — i w końcu dostał wszystko: tytuł królewski, uznaną metropolię kościelną i granice sięgające Łaby i Karpat. Zjazd Gnieźnieński w 1000 roku był jego teatralnym arcydziełem: cesarz Otto III ukląkł przy grobie świętego Wojciecha i własną cesarską koroną ozdobił skroń Bolesława.\n\nKoronacja 25 lat później przyszła na łożu śmierci — ale umarł jako król. Umarł 17 czerwca 1025 roku w Poznaniu. Pochowany w katedrze poznańskiej.", en:"The first King of Poland, conqueror, diplomat, and builder of the Polish Church.\n\nKey dates: 992 — took power after his father Mieszko I, immediately expelling his half-brothers and stepmother Oda; 1000 — Congress of Gniezno: Emperor Otto III recognised a Polish archbishopric and placed his own imperial crown on Bolesław's head; 1002–1018 — prolonged wars with the Empire over Lusatia and Meissen; 1018 — seizure of Kyiv and recovery of the Red Ruthenian cities; 1025 — royal coronation, the first in Polish history.\n\nHe had four wives: an unnamed daughter of Margrave Rikdag of Meissen (c. 984–987), Judith of Hungary (c. 987–992), Emnilda of Lusatia (992–1017) — the one who mattered most, mother of his principal heirs — and Oda of Meissen (after 1018). He had at least seven children, including Bezprym, Mieszko II and Otto by Emnilda, and Regelinda.\n\nHe spent his entire reign expanding, and in the end he got everything: a royal crown, a recognised archdiocese, and borders that reached the Elbe and the Carpathians. The Congress of Gniezno in 1000 was his theatrical masterstroke: Emperor Otto III knelt at the tomb of St. Adalbert and placed his own imperial diadem on Bolesław's head.\n\nThe royal coronation came 25 years later on his deathbed — but he died a king. He died on 17 June 1025 in Poznań and is buried in Poznań Cathedral." }},

    { id:"emnilda", fn:"Emnilda", ln:"z Łużyc", g:"F", b:"975", d:"1017",
      bp:"Łużyce", dp:"Polska", nat:"DE", p:[], s:["boleslaw1"], image:null,
      bio:{ pl:"Trzecia żona — ta, która liczyła się najbardziej. Jej łużyckie koneksje dynastyczne legitymizowały zachodnie kampanie Bolesława, a ona dała mu następców tronu. Umarła przed mężem i historia nie zachowała niemal nic o niej osobiście — co jest własnym rodzajem świadectwa, jak mało wart był kobiecy żywot zdaniem kronikarzy.", en:"Third wife — the one who mattered most. Her Lusatian family connections legitimised Bolesław's western campaigns, and she gave him his heirs. She died before her husband, and history recorded almost nothing about her personally — which is its own kind of testament to how little women's lives were thought worth recording." }},

    { id:"nn_misnska", fn:"N.N.", ln:"z Miśni", g:"F", b:"~968", d:"po 987",
      bp:"Miśnia, Niemcy", dp:"Niemcy", nat:"DE", p:[], s:["boleslaw1"], image:null,
      bio:{ pl:"Pierwsza żona Bolesława Chrobrego — nieznana z imienia córka margrabiego Rikdaga z Miśni. Małżeństwo zawarto około 984 roku jako dynastyczny sojusz z marchią wschodnią; Bolesław oddalił ją około 987. Prawdopodobnie to ona — a nie Emnilda — była matką Bezpryma: Bezprym urodził się około 986, na sześć lat przed ślubem Bolesława z Emnildą. Oddalona i zapomniana przez roczniki, żyje w historii wyłącznie przez syna, który niemal zawładnął Polską.", en:"First wife of Bolesław Chrobry — name unknown, daughter of Margrave Rikdag of Meissen. The marriage was concluded around 984 as a dynastic alliance with the eastern march; Bolesław repudiated her around 987. She was most likely Bezprym's mother: Bezprym was born around 986, six years before Bolesław's marriage to Emnilda. Repudiated and forgotten by the chronicles, she survives in history only through the son who nearly seized Poland." }},

    { id:"judith_wegierska", fn:"Judyta", ln:"Węgierska", g:"F", b:"~974", d:"po 991",
      bp:"Węgry", dp:"Polska", nat:"HU", p:[], s:["boleslaw1"], image:null,
      bio:{ pl:"Druga żona Bolesława Chrobrego — węgierska księżniczka pojęta dla przymierza z Arpadami, a następnie oddalona. Małżeństwo trwało zaledwie kilka lat i nie pozostawiło zidentyfikowanych potomków. Węgierskie koneksje nawiązane w tym czasie mogły jednak posłużyć Bolesławowi podczas późniejszych interwencji zbrojnych na południu — wystarczy spojrzeć, gdzie umarł wygnany brat Bezprym.", en:"Second wife of Bolesław Chrobry — a Hungarian princess taken for political alliance with the Árpáds, then repudiated. The marriage lasted only a few years and left no identified children. The Hungarian connections established at this time may nonetheless have served Bolesław during his later armed interventions in the south — Bezprym's exile and death in Hungary is reminder enough." }},

    { id:"regelinda_piast", fn:"Regelinda", ln:"Piastówna", g:"F", b:"~989", d:"po 1014",
      bp:"Polska", dp:"Niemcy", nat:"PL", p:["boleslaw1","emnilda"], s:[], image:null,
      bio:{ pl:"Córka Bolesława Chrobrego i Emnildy — oddana na zachód jako żona Hermana I, margrabiego Miśni, w ramach pokoju merseburskiego z 1013 roku kończącego wieloletnie wojny polsko-cesarskie. Jej ślub był dyplomatyczną pieczęcią porozumienia między Polską a cesarstwem. Tradycja historyczna łączy ją z Regelindą — jedną z rzeźbionych figur fundatorskich katedry w Naumburgu. Przez jej małżeństwo krew Piastów wlała się do dynastii marchii wschodniej Rzeszy.", en:"Daughter of Bolesław Chrobry and Emnilda — sent west as wife to Herman I, Margrave of Meissen, as part of the Peace of Merseburg in 1013 that ended years of Polish-Imperial warfare. Her marriage was the diplomatic seal on that agreement between Poland and the Empire. Historical tradition identifies her with Regelinda — one of the sculpted founder figures of Naumburg Cathedral. Through her marriage, Piast blood entered one of the key dynasties of the Empire's eastern marches." }},

    { id:"bezprym", fn:"Bezprym", ln:"Piast", g:"M", b:"986", d:"1032", rs:"1031", re:"1032",
      bp:"Polska", dp:"Polska", nat:"PL", p:["boleslaw1","nn_misnska"], s:[], image:null, map:"maps/1032.jpg",
      bio:{ pl:"Syn Bolesława Chrobrego z pierwszego małżeństwa — jego matką była prawdopodobnie córka margrabiego Rikdaga z Miśni, oddalona przez ojca jeszcze przed ślubem z Emnildą. Najstarszy, a więc i pierwszy wykluczony: odsunięty do klasztoru, gdy koronę przeznaczono dla później urodzonego Mieszka II. Spędził dziesięciolecia obserwując, jak brat rządzi królestwem, które powinno było być jego — po czym zdobył je w 1031 roku i został zamordowany przez własnych dworzan w ciągu roku. Życie cierpliwości nagrodzone rokiem władzy i gwałtownym końcem.", en:"Son of Bolesław Chrobry from his first marriage — his mother was most likely the daughter of Margrave Rikdag of Meissen, repudiated by his father before the marriage to Emnilda. The eldest son, and so the first to be excluded: set aside for a monastery while the crown was reserved for the later-born Mieszko II. He spent decades watching his brother rule what should have been his kingdom, then seized it in 1031 — and was murdered by his own courtiers within a year. A life of patience rewarded with a year of power and a violent end." }},

    { id:"mieszko2", fn:"Mieszko II", ln:"Lambert", g:"M", b:"990", d:"1034", rs:"1025", re:"1034",
      bp:"Polska", dp:"Polska", nat:"PL", p:["boleslaw1","emnilda"], s:["rycheza"], image:"Matejko_Stroynowski_Papieski/mieszko_ii_lambert.jpg", map:"maps/1032.jpg",
      bio:{ pl:"Odziedziczył imperium i utracił większość z niego. Mieszko II był wykształcony, oczytany — prawdopodobnie najuczeńszy król swojego pokolenia, prowadził po łacinie korespondencję z niemieckimi ksieniami. Na nic się to nie zdało, gdy bracia podnieśli bunt, Czesi splądrowali Kraków, a królestwo sypało się ze wszystkich stron.", en:"He inherited an empire and lost most of it. Mieszko II was educated, literate — probably the most learned king of his generation, corresponding in Latin with German abbesses. None of it helped when his brothers rose against him, the Bohemians pillaged Kraków, and the kingdom unravelled around him." }},

    { id:"rycheza", fn:"Rycheza", ln:"z Lotaryngii", g:"F", b:"995", d:"1063",
      bp:"Lotaryngia", dp:"Niemcy", nat:"DE", p:[], s:["mieszko2"], image:"Matejko_Stroynowski_Papieski/rycheza_lotarynska.jpg",
      bio:{ pl:"Córka palatyna Ezzo Lotaryńskiego i bratanica cesarza Ottona III — jedna z najlepiej skoligaconych księżniczek swojej epoki. Poślubiła Mieszka II w 1013 roku i stała się pierwszą koronowaną królową Polski. Gdy w latach 1031–1032 królestwo runęło pod ciosami buntu możnowładców, czeskiego najazdu Brzetysława i ruskiej interwencji Jarosława Mądrego — Rycheza nie uciekła. Wyjechała celowo. Zabrała ze sobą polskie regalia królewskie, upewniając się, że jeśli Polska ma znów być królestwem, będzie musiała prosić jej rodziny o insygnia. Przeżyła męża o 32 lata.", en:"Daughter of Count Palatine Ezzo of Lorraine and great-niece of Emperor Otto III — among the best-connected princesses of her generation. She married Mieszko II in 1013 and became the first crowned Queen of Poland. When the kingdom collapsed between 1031 and 1032 — under a nobles' revolt, a Bohemian invasion by Bretislaus, and a Rus' intervention by Yaroslav the Wise — Rycheza did not flee. She left deliberately, taking the Polish crown regalia with her, ensuring that if Poland was to be a kingdom again, it would have to ask her family for the insignia. She outlived Mieszko by 32 years." }},

    { id:"gertruda_piastowna", fn:"Gertruda", ln:"Piastówna", g:"F", b:"~1025", d:"~1109",
      bp:"Polska", dp:"Ruś Kijowska", nat:"PL", p:["mieszko2","rycheza"], s:[], image:null,
      bio:{ pl:"Córka Mieszka II i Rychezy, wysłana na wschód jako żona Izjasława I Jarosławowicza, wielkiego księcia kijowskiego. Razem z mężem przeżyła dwa wygnania i dwa powroty na kijowski tron. Po jego śmierci w 1078 roku żyła jeszcze blisko trzy dziesięciolecia. Pozostawiła po sobie Kodeks Gertrudy — własnoręcznie uzupełniany psałterz z łacińskimi modlitwami pełnymi trwogi o los syna Jaropełka. To jeden z najintymniejszych dokumentów osobistych z Polski średniowiecznej — pisany przez kobietę, która widziała egzylowaną matkę, zamordowanego ojca i syna walczącego o kijowski tron.", en:"Daughter of Mieszko II and Rycheza, sent east as wife to Iziaslav I of Kyiv. She shared two exiles with her husband and two returns to the throne. After his death in 1078 she lived nearly three more decades. She left behind the Codex of Gertrude — a psalter supplemented in her own hand with Latin prayers full of anguish over her son Yaropolk's fate. It is one of the most intimate personal documents to survive from medieval Poland, written by a woman who had watched her mother exiled, her father murdered, and her son fighting for the Kyivan throne." }},

    { id:"kazimierz1", fn:"Kazimierz I", ln:"Odnowiciel", g:"M", b:"1016", d:"1058", rs:"1039", re:"1058",
      bp:"Polska", dp:"Poznań, Polska", nat:"PL", p:["mieszko2","rycheza"], s:["dobroniega"], image:"Matejko_Stroynowski_Papieski/kazimierz_i_odnowiciel.jpg", map:"maps/1039-1058.png",
      bio:{ pl:"Kraj, który odziedziczył, był gruzowiskiem. Pogańskie bunty, najazd czeski, możnowładcy walczący ze sobą — Kazimierz znalazł królestwo rozsypane po leśnym dnie. Spędził całe panowanie zbierając kawałki: przeniósł stolicę ze zrujnowanego Gniezna do Krakowa, odbudował klasztory, i umarł mając 42 lata — nie wiedząc, czy przetrwa.", en:"The country he inherited was rubble. Pagan revolt, Bohemian invasion, nobility fighting nobility — Kazimierz found a kingdom scattered across the forest floor. He spent his entire reign picking up the pieces, moving the capital from shattered Gniezno to Kraków, rebuilding monasteries, and dying at 42 before he could see whether it would hold." }},

    { id:"dobroniega", fn:"Maria Dobroniega", ln:"z Kijowa", g:"F", b:"1012", d:"1087",
      bp:"Kijów, Ruś", dp:"Polska", nat:"RUS", p:[], s:["kazimierz1"], image:null,
      bio:{ pl:"Córka Włodzimierza Wielkiego z Kijowa — jednej z najpotężniejszych dynastii na wschód od Polski — wniosła w małżeństwo z Kazimierzem Odnowicielem nie tylko rurykowicki prestiż, ale i polityczne połączenie z Rusią Kijowską. Przez jej synów — Bolesława Szczodrego i Władysława Hermana — krew Rurykowiczów płynęła w żyłach każdego kolejnego Piasta.", en:"Daughter of Vladimir the Great of Kyiv — one of the most powerful dynasties east of Poland — she brought into her marriage with Kazimierz the Restorer not just Rurikid prestige but a political bond with Kievan Rus. Through her sons — Bolesław the Bold and Władysław Herman — the blood of the Rurikids ran through every future Piast king." }},

    { id:"boleslaw2", fn:"Bolesław II", ln:"Szczodry", g:"M", b:"1042", d:"1081", rs:"1058", re:"1079",
      bp:"Polska", dp:"Węgry", nat:"PL", p:["kazimierz1","dobroniega"], s:[], image:"Matejko_Stroynowski_Papieski/boleslaw_ii_szczodry.jpg", map:"maps/1097.svg.png",
      bio:{ pl:"Zabił biskupa i stracił królestwo. Bolesław II był prawdziwym królem-wojownikiem — przywrócił tytuł królewski, walczył na trzech frontach, wysyłał armie na Węgry i Ruś. Potem w 1079 roku kazał zabić biskupa Stanisława ze Szczepanowa — z wściekłości lub zimnej kalkulacji politycznej — i wywołany tym wstrząs wygnał go z Polski na zawsze. Umarł na węgierskim wygnaniu, prawdopodobnie zamordowany.", en:"He killed a bishop and lost a kingdom. Bolesław II was a true warrior-king — he restored the royal title, fought across three frontiers, sent armies into Hungary and Russia. Then in 1079 he executed Bishop Stanisław of Szczepanów — in rage or cold political calculation — and the backlash drove him from Poland forever. He died in Hungarian exile, probably murdered." }},

    { id:"wladyslaw1h", fn:"Władysław I", ln:"Herman", g:"M", b:"1043", d:"1102", rs:"1079", re:"1102",
      bp:"Polska", dp:"Płock, Polska", nat:"PL", p:["kazimierz1","dobroniega"], s:["judith_boh","judith_szwabska"], image:"Matejko_Stroynowski_Papieski/wladyslaw_i_herman.jpg", map:"maps/1097.svg.png",
      bio:{ pl:"Władza w jego księstwie spoczywała w rękach jednego człowieka: palatyna Sieciecha. Władysław Herman był fizycznie słaby i politycznie bierny, a Sieciech wypełnił tę próżnię tak całkowicie, że jego własni synowie musieli się w końcu zbuntować, by go odsunąć. Panowanie trwające 23 lata, zapamiętane głównie przez pryzmat swojego administratora.", en:"Power in his duchy ran through one man: the palatine Sieciech. Władysław Herman was physically weak and politically passive, and Sieciech filled the vacuum so completely that his own sons eventually had to rebel to dislodge him. A reign of 23 years remembered mostly for its administrator." }},

    { id:"judith_boh", fn:"Judyta", ln:"Czeska", g:"F", b:"1058", d:"1086",
      bp:"Bohemia", dp:"Polska", nat:"CZ", p:[], s:["wladyslaw1h"], image:null,
      bio:{ pl:"Umarła młodo — mając 28 lat, kilka miesięcy po narodzinach syna Bolesława Krzywoustego. Kroniki odnotowują, że była piękna i pobożna. Jej czeskie pochodzenie dało mężowi dynastyczne połączenie na zachodzie; jej śmierć dała mu pretekst do powtórnego małżeństwa i skomplikowania sukcesji.", en:"She died young — at 28, just months after her son Bolesław Wrymouth was born — possibly in childbirth. The chronicles note she was beautiful and pious. Her Bohemian origins gave her husband a dynastic connection west; her death gave him reason to remarry and complicate the succession." }},

    { id:"judith_szwabska", fn:"Judyta", ln:"Szwabska", g:"F", b:"~1054", d:"1091",
      bp:"Niemcy", dp:"Polska", nat:"DE", p:[], s:["wladyslaw1h"], image:null,
      bio:{ pl:"Córka cesarza Henryka IV — księżniczka wysłana do Polski u szczytu sporu o inwestyturę między papiestwem a cesarstwem. Małżeństwo z Władysławem Hermanem w 1088 roku dało polskiemu księciu bezprecedensowe powiązanie z Rzeszą w chwili, gdy Europa rozrywała się między Grzegorzem VII a Henrykiem IV. Judyta umarła trzy lata po ślubie, nie zostawiając potomków — samo zawarcie tego małżeństwa było jednak politycznym oświadczeniem.", en:"Daughter of Emperor Henry IV — a princess sent to Poland at the height of the Investiture Controversy. Her marriage to Władysław Herman in 1088 gave the Polish duke an unprecedented link to the empire at the moment when Europe was tearing itself apart between Gregory VII and Henry IV. Judith died three years later without children — but the marriage itself had been a political statement." }},

    { id:"zbigniew", fn:"Zbigniew", ln:"Piast", g:"M", b:"1070", d:"1113",
      bp:"Polska", dp:"Polska", nat:"PL", p:["wladyslaw1h"], s:[], image:null,
      bio:{ pl:"Spędził lata jako prawy dziedzic, który nie chciał zniknąć. Zbigniew współrządził z przyrodnim bratem Bolesławem, każdy z nich podnosił armię przeciw drugiemu, każdy przegrywał i zawierał pokój — aż Bolesław w końcu kazał go oślepić. Niedługo potem umarł. Tragedia starszego syna: nigdy do końca nie król, nigdy do końca nie poddany.", en:"He spent years as the legitimate heir who wouldn't quite go away. Zbigniew co-ruled with his half-brother Bolesław, each raising armies against the other, each losing and making peace, until Bolesław finally had him blinded. He died shortly after. An elder son's tragedy: never quite the king, never quite not." }},

    { id:"boleslaw3", fn:"Bolesław III", ln:"Krzywousty", g:"M", b:"1086", d:"1138", rs:"1102", re:"1138",
      bp:"Polska", dp:"Sochaczew, Polska", nat:"PL", p:["wladyslaw1h","judith_boh"], s:["zbyslaw","salomea"], image:"Matejko_Stroynowski_Papieski/boleslaw_iii_krzywousty.jpg", map:"maps/1102-1138.png",
      bio:{ pl:"Skonsolidował wszystko, co dynastia zbudowała — a potem w swoim testamencie to systematycznie zniszczył. Bolesław Krzywousty pokonał cesarza Henryka V, podbił Pomorze, oślepił własnego brata — wszystko w służbie polskiego państwa, które następnie podzielił na pięć kawałków dla synów. Testament z 1138 roku zapoczątkował 182 lata rozbicia. Każda późniejsza wojna, każda utracona prowincja, prowadzi do tamtego dokumentu.", en:"He consolidated everything his dynasty had built and then, in his will, systematically destroyed it. Bolesław Wrymouth beat the Holy Roman Emperor, conquered Pomerania, and blinded his own brother — all in the service of a Polish state he would then divide into five pieces for his sons. The testament of 1138 began 182 years of fragmentation. Every war, every lost province of the next two centuries leads back to that document." }},

    { id:"zbyslaw", fn:"Zbysława", ln:"Kijowska", g:"F", b:"1085", d:"1110",
      bp:"Kijów, Ruś", dp:"Polska", nat:"RUS", p:[], s:["boleslaw3"], image:null,
      bio:{ pl:"Kijowska księżniczka — córka wielkiego księcia Świętopełka II — która przybyła na zachód poślubić najbardziej ambitnego polskiego księcia epoki. Urodziła Bolesławowi jego najstarszego prawowitego syna, Władysława Wygnańca, i zmarła mając 25 lat. Krew Rurykowiczów, którą wniosła, popłynie przez śląską linię Piastów.", en:"A Kievan princess — daughter of Grand Prince Sviatopolk II — who came west to marry the most ambitious Polish duke of the age. She bore Bolesław his eldest legitimate son, Władysław the Exile, before dying at 25. The Rurikid blood she brought would run through the Silesian Piast line." }},

    { id:"salomea", fn:"Salomea", ln:"z Bergu", g:"F", b:"1101", d:"1144",
      bp:"Berg, Niemcy", dp:"Polska", nat:"DE", p:[], s:["boleslaw3"], image:null,
      bio:{ pl:"Przeżyła męża o sześć lat i pochowała większość ambicji swoich dzieci — a przynajmniej próbowała, wstępując pod koniec życia do klasztoru. Jej synowie dostali dzielnice wydzielone przez testament Bolesława i spędzili następne pokolenie walcząc między sobą o resztki.", en:"She outlived her husband by six years and buried most of her children's ambitions with her — or tried to, entering a convent at the end of her life. Her sons received the principalities Bolesław's testament carved out, and spent the next generation fighting each other over the scraps." }},

    { id:"ryksa_piastowna", fn:"Ryksa", ln:"Piastówna", g:"F", b:"~1116", d:"1185",
      bp:"Polska", dp:"Niemcy", nat:"PL", p:["boleslaw3","salomea"], s:[], image:null,
      bio:{ pl:"Córka Bolesława Krzywoustego i Salomei z Bergu — przez jej małżeństwa dynastia Piastów roztknęła więzi na dwa krańce ówczesnej Europy. Pierwsze małżeństwo zaprowadziło ją do Skandynawii: poślubiła Magnusa Nielssona, syna króla Danii Nielsa. Po jego śmierci trafiła na wschód — za Wsiewołoda ze Szlązka. Przeżyła obie te epoki i umarła w 1185 roku, dzieląc losy wielu piastowskich księżniczek: wysłanych na obcą rubież, zapamiętanych przez kroniki w strzępach.", en:"Daughter of Bolesław Wrymouth and Salomea of Berg — through her marriages the Piast dynasty cast threads to two ends of the contemporary world. Her first marriage took her to Scandinavia: she married Magnus Nielsen, son of King Niels of Denmark. After his death she went east. She outlived both these chapters and died in 1185, sharing the fate of many Piast princesses: dispatched to a foreign frontier, remembered in the chronicles only in fragments." }},

    { id:"judyta_piastowna", fn:"Judyta", ln:"Piastówna", g:"F", b:"~1118", d:"po 1150",
      bp:"Polska", dp:"Czechy", nat:"PL", p:["boleslaw3","salomea"], s:[], image:null,
      bio:{ pl:"Córka Bolesława Krzywoustego i Salomei z Bergu, poślubiona Władysławowi II, przyszłemu królowi Czech. Jej małżeństwo zawarto w 1138 roku — tym samym, w którym testament ojca rozbił Polskę na dzielnice. Judyta udała się do Pragi, gdy jej bracia zaczynali pierwsze z długich wojen o starszeństwo. Przez jej potomków krew Piastów dotarła na czeski tron i splotła się z rodem Przemyślidów.", en:"Daughter of Bolesław Wrymouth and Salomea of Berg, married to Vladislaus II, future King of Bohemia. Her marriage was concluded in 1138 — the same year her father's testament fractured Poland into principalities. Judyta left for Prague as her brothers were beginning the first of their long wars over seniority. Through her descendants, Piast blood reached the Bohemian throne and intertwined with the Přemyslid line." }},

    { id:"wladyslaw2wygn", fn:"Władysław II", ln:"Wygnaniec", g:"M", b:"1105", d:"1159",
      bp:"Polska", dp:"Niemcy", nat:"PL", p:["boleslaw3","zbyslaw"], s:[], image:"Matejko_Stroynowski_Papieski/wladyslaw_ii_wygnaniec.jpg", map:"maps/fragmentation.jpg",
      bio:{ pl:"Miał być seniorem dynastii — pierwszym spośród równych — na tym polegał cały sens testamentu ojca. Bracia się nie zgodzili. Władysław Wygnaniec został wypędzony z Polski w 1146 roku i nigdy nie wrócił, choć przez lata błagał cesarza o armię, która go przywróci. Umarł na niemieckim wygnaniu w 1159 roku. Jego potomkowie, śląscy Piastowie, wystawią więcej pretendentów do polskiego tronu niż jakakolwiek inna gałąź dynastii.", en:"He was supposed to be the senior duke, first among equals — that was the whole point of his father's testament. His brothers disagreed. Władysław the Exile was driven from Poland in 1146 and never came back, though he spent years petitioning the Holy Roman Emperor for an army to restore him. He died in German exile in 1159. His descendants, the Silesian Piasts, would produce more claimants to the Polish throne than any other branch." }},

    { id:"boleslaw4", fn:"Bolesław IV", ln:"Kędzierzawy", g:"M", b:"1125", d:"1173", rs:"1146", re:"1173",
      bp:"Polska", dp:"Polska", nat:"PL", p:["boleslaw3","salomea"], s:[], image:"Matejko_Stroynowski_Papieski/boleslaw_iv_kedzierzawy.jpg", map:"maps/fragmentation.jpg",
      bio:{ pl:"To on trzymał centrum — Mazowsze i Kraków — po wygnaniu brata Władysława. Nie był władcą spektakularnym, ale solidnym: odpierał niemieckich cesarzy, gdy przychodzili egzekwować restaurację Władysława, organizował obronę przed najazdami pruskimi i oddał królestwo w mniej rozdrobnionym stanie, niż je zastał.", en:"He was the one who held the centre — Mazovia and Kraków — after his brother Władysław's exile. Not a spectacular ruler, but a steady one: he kept German emperors at bay when they came to enforce Władysław's restoration, organised defence against Prussian raids, and handed on a kingdom less fragmented than he found it." }},

    { id:"mieszko3", fn:"Mieszko III", ln:"Stary", g:"M", b:"1126", d:"1202", rs:"1173", re:"1202",
      bp:"Polska", dp:"Kalisz, Polska", nat:"PL", p:["boleslaw3","salomea"], s:[], image:"Matejko_Stroynowski_Papieski/mieszko_iii_stary.jpg", map:"maps/1177-1194.png",
      bio:{ pl:"Chciał być królem w epoce, która królestwo zniosła. Mieszko Stary był najdłużej żyjącym Piastem okresu rozbicia — prawie 76 lat — i większość z nich spędził walcząc o Kraków, który już nie uznawał żadnego seniora dynastii w żadnym sensownym znaczeniu. Dwa razy go wygnano. Dwa razy wrócił. Umarł trzymając Kraków.", en:"He wanted to be king in an age that had abolished kings. Mieszko the Old was the longest-lived Piast of the fragmentation era — nearly 76 years — and spent most of them fighting for Kraków, which no longer recognised a senior duke in any meaningful sense. He was expelled twice. He came back twice. He died holding Kraków." }},

    { id:"kazimierz2", fn:"Kazimierz II", ln:"Sprawiedliwy", g:"M", b:"1138", d:"1194", rs:"1177", re:"1194",
      bp:"Polska", dp:"Kraków, Polska", nat:"PL", p:["boleslaw3","salomea"], s:["helena_znojemska"], image:"Matejko_Stroynowski_Papieski/kazimierz_ii_sprawiedliwy.jpg", map:"maps/1177-1194.png",
      bio:{ pl:"'Sprawiedliwy' — tytuł nadany przez tych, którzy uznali go za łagodnego, był w tej epoce naprawdę rzadki. Kazimierz II utrzymywał pokój przez akomodację Kościoła i możnowładców, reformował prawo i zarządzał niemożliwą sztuką równowagi w czasach, gdy każdy książę knuł przeciw każdemu innemu. Jego prawdziwym osiągnięciem było to, że Polska była przy jego śmierci nieco mniej rozbita niż gdy przejmował władzę.", en:"'The Just' — a title given by those who found him mild — was genuinely rare in the era. He kept the peace by accommodating the Church and the magnates, reformed the laws, and managed the impossible balancing act of ruling in an age when every duke was plotting against every other. His real achievement was that Poland was slightly less broken when he died than when he took power." }},

    { id:"helena_znojemska", fn:"Helena", ln:"Znojemska", g:"F", b:"~1159", d:"1202",
      bp:"Znojmo, Morawy", dp:"Kraków, Polska", nat:"CZ", p:[], s:["kazimierz2"], image:null,
      bio:{ pl:"Córka Konrada III ze Znojma, wniosła do małżeństwa z Kazimierzem II cenne koneksje czeskie. Przez lata stała u boku męża podczas jego ostrożnej gry między możnymi a Kościołem. Przeżyła go o osiem lat, być może towarzysząc dworowi podczas walk o schedę. Los sprawił, że jej syn Konrad zaprosi Krzyżaków — decyzja, której Helena nigdy nie dożyła ani nie mogła przewidzieć.", en:"Daughter of Konrad III of Znojmo, she brought valuable Bohemian connections to her marriage with Kazimierz II. She stood by her husband through his careful balancing act between the magnates and the Church, and outlived him by eight years. Fate would make her son Konrad responsible for inviting the Teutonic Knights into Poland — a catastrophe she neither lived to see nor could have imagined." }},

    { id:"leszek1", fn:"Leszek I", ln:"Biały", g:"M", b:"1184", d:"1227", rs:"1194", re:"1227",
      bp:"Polska", dp:"Gąsawa, Polska", nat:"PL", p:["kazimierz2","helena_znojemska"], s:["grzymislawa"], image:"Matejko_Stroynowski_Papieski/leszek_bialy.jpg", map:"maps/1190.svg.png",
      bio:{ pl:"Zamordowano go na zjeździe. Kongres w Gąsawie w 1227 roku miał rozstrzygnąć spór między polskimi książętami; zamiast tego Henryk Brodaty zaatakował, a Leszek Biały zginął w chaosie. Był jednym z zdolniejszych władców okresu rozbicia — jego błędem było zaufanie nieodpowiednim ludziom na naradzie.", en:"He was murdered at a summit. The Congress of Gąsawa in 1227 was supposed to settle a dispute between Polish dukes; instead Henry the Bearded attacked, and Leszek the White was killed in the chaos. He had been one of the more capable rulers of the fragmentation era — his mistake was trusting the wrong people at a meeting." }},

    { id:"grzymislawa", fn:"Grzymisława", ln:"Ruska", g:"F", b:"~1190", d:"po 1258",
      bp:"Ruś", dp:"Kraków, Polska", nat:"RUS", p:[], s:["leszek1"], image:null,
      bio:{ pl:"Ruska księżniczka, żona Leszka I Białego — jej dokładne pochodzenie pozostaje przedmiotem sporu historyków. Gdy Leszek zginął na zjeździe w Gąsawie w 1227 roku, ich syn Bolesław Wstydliwy miał zaledwie rok. Grzymisława sprawowała regencję przez kilkanaście lat, broniąc małopolskiej dzielnicy przed magnackimi rywalizacjami i obcą interwencją. Przeżyła większość swoich współczesnych, ostatni raz pojawiając się w źródłach po 1258 roku.", en:"A Ruthenian princess, wife of Leszek the White — her exact origins remain disputed among historians. When Leszek was killed at the summit of Gąsawa in 1227, their son Bolesław the Chaste was barely a year old. Grzymisława held the regency for over a decade, defending the Lesser Polish principality against magnate rivalries and foreign intervention. She outlived most of her contemporaries, last appearing in the sources after 1258." }},

    { id:"konrad_i_mazowiecki", fn:"Konrad I", ln:"Mazowiecki", g:"M", b:"~1187", d:"1247-08-31",
      bp:"Mazowsze, Polska", dp:"Czersk, Polska", nat:"PL", p:["kazimierz2","helena_znojemska"], s:["agafia_swiatoslawowna"], image:"Matejko_Stroynowski_Papieski/konrad_i_mazowiecki.jpg",
      bio:{ pl:"Zapraszając Krzyżaków w 1226 roku do obrony przed Prusami, Konrad I rozwiązał jeden problem — i stworzył inny, który nękał Polskę przez 500 lat. Nie był głupcem: był pragmatykiem otoczonym wrogami ze wszystkich stron. Walczył z Prusami, rywalizował z bratem Leszkiem o Kraków, toczył niekończące się spory z biskupami. Krzyżacy mieli bronić granicy. Zamiast tego ją wchłonęli.", en:"By inviting the Teutonic Knights in 1226 to defend against the Prussians, Konrad I solved one problem and created another that would haunt Poland for 500 years. He was no fool — he was a pragmatist surrounded by enemies on all sides, fighting Prussians, rivalling his brother Leszek for Kraków, locked in endless dispute with the bishops. The Knights were meant to guard a border. Instead, they swallowed it." }},

    { id:"agafia_swiatoslawowna", fn:"Agafia", ln:"Światosławówna", g:"F", b:"~1195", d:"~1239",
      bp:"Ruś (Czernihów)", dp:"Mazowsze, Polska", nat:"RUS", p:[], s:["konrad_i_mazowiecki"], image:"Matejko_Stroynowski_Papieski/agafa_swiatoslawowna.jpg",
      bio:{ pl:"Ruska księżniczka, która poprzez małżeństwo z Konradem I splotła losy dynastii Rurykowiczów z mazowieckimi Piastami. Jej synowie podzielili między siebie schedę ojca — Kazimierz wziął Kujawy, Siemowit Mazowsze. Mało o niej wiadomo, lecz ślady wschodniej kultury dworskiej widać w imionach nadawanych dzieciom.", en:"A Rus' princess who wove the Rurikid dynasty into the Masovian Piasts through her marriage to Konrad I. Her sons divided their father's inheritance — Kazimierz took Kujawy, Siemowit took Masovia. Little is recorded of her directly, but the eastern court culture she brought is reflected in the names given to her children." }},

    { id:"kazimierz_i_kujawski", fn:"Kazimierz I", ln:"Kujawski", g:"M", b:"~1211", d:"1267-12-14",
      bp:"Mazowsze, Polska", dp:"Inowrocław, Polska", nat:"PL", p:["konrad_i_mazowiecki","agafia_swiatoslawowna"], s:["konstancja_wroclawska","eufrozyna_opolska"], image:null,
      bio:{ pl:"Miał dwie żony i tyle dzieci, że samo rozdzielenie między nimi schedę zajęło dziesięciolecia. Z pierwszą — Konstancją — miał Leszka Czarnego; z drugą, Eufrozyną — Władysława Łokietka i Jadwigę. To ostatnie małżeństwo budziło zdziwienie współczesnych: Jadwiga i Władysław byli rodzeństwem, a mimo to później pobrali się. Kazimierz I nie dożył, by zobaczyć swojego syna królem.", en:"He had two wives and so many children that dividing the inheritance between them took decades. With his first wife Konstancja he fathered Leszek the Black; with his second, Eufrozyna — Władysław Łokietek and Jadwiga. That last arrangement puzzled contemporaries: Jadwiga and Władysław were siblings, yet they later married. Kazimierz I did not live to see his son become king." }},

    { id:"konstancja_wroclawska", fn:"Konstancja", ln:"Wrocławska", g:"F", b:"~1221", d:"~1257",
      bp:"Wrocław, Śląsk", dp:"Kujawy, Polska", nat:"PL", p:["henryk2p","anna_przemyslidka"], s:["kazimierz_i_kujawski"], image:null,
      bio:{ pl:"Miała zaledwie kilkanaście lat, gdy jej ojciec Henryk II zginął pod Legnicą walcząc z Mongołami — stała się sierotą i symbolem dramatu jednocześnie. Kiedy poślubiła Kazimierza I Kujawskiego, była nośnikiem śląskiego prestiżu w kujawskim domu. Jej syn Leszek Czarny zostanie księciem krakowskim, choć ona sama nie dożyje jego chwały.", en:"She was barely a teenager when her father Henryk II died at Legnica fighting the Mongols — simultaneously an orphan and a symbol of that catastrophe. When she married Kazimierz I of Kujawy she brought Silesian prestige to a Kuyavian house. Her son Leszek the Black would become Duke of Kraków, though she would not live to see his rise." }},

    { id:"ziemomysl_kuj", fn:"Ziemomysł", ln:"Kujawski", g:"M", b:"~1248", d:"1287",
      bp:"Kujawy, Polska", dp:"Inowrocław, Polska", nat:"PL", p:["kazimierz_i_kujawski","konstancja_wroclawska"], s:[], image:null,
      bio:{ pl:"Syn Kazimierza I i Konstancji, otrzymał Inowrocław jako swoją część ojcowskiej schedy. Rządził nim do śmierci w 1287 roku, nie zostawiając potomstwa. Dzielnica wróciła do linii jego przyrodniego brata Władysława Łokietka. Historia zachowała o nim niewiele: był księciem, który trzymał swoją część bez wielkiego triumfu ani wielkiej katastrofy — co w XIII wieku było samo w sobie osiągnięciem.", en:"Son of Kazimierz I and Konstancja, he received Inowrocław as his share of his father's inheritance and ruled it until his death in 1287, leaving no children. His duchy reverted to the line of his half-brother Władysław Łokietek. History recorded little about him: a duke who held his portion without great triumph or great disaster — which in the thirteenth century was itself an achievement." }},

    { id:"euphemia_kuj", fn:"Eufemia", ln:"Kujawska", g:"F", b:"~1253", d:"~1298",
      bp:"Kujawy, Polska", dp:"Polska", nat:"PL", p:["kazimierz_i_kujawski","konstancja_wroclawska"], s:[], image:null,
      bio:{ pl:"Opuściła kujawskie dwory braci i wyjechała na Pomorze, poślubiając Mściwoja II — ostatniego niezależnego księcia Pomorza Gdańskiego. Jej małżeństwo było geografią dynastyczną: wiązało kujawskich Piastów z wybrzeżem w chwili, gdy oba kraje znajdowały się pod presją Brandenburgii i Zakonu Krzyżackiego. Czy kształtowała politykę Mściwoja, czy zostawiła przeżywających potomków — kroniki dają jedynie strzępy.", en:"She left the Kuyavian courts of her brothers for Pomerania, marrying Mestwin II — the last independent Duke of Gdańsk Pomerania. Her marriage was dynastic geography: binding the Piasts of Kujawy to the coast at a moment when both were under pressure from Brandenburg and the Teutonic Knights. Whether she shaped Mestwin's politics or left surviving children, the records give only fragments." }},

    { id:"eufrozyna_opolska", fn:"Eufrozyna", ln:"Opolska", g:"F", b:"~1230", d:"~1292",
      bp:"Opole, Śląsk", dp:"Kujawy, Polska", nat:"PL", p:[], s:["kazimierz_i_kujawski"], image:null,
      bio:{ pl:"Dożyła ponad sześćdziesięciu lat, co na owe czasy graniczyło z cudem. Przeżyła męża, przeżyła wielu jego synów, a jej własny syn Władysław przez dziesięciolecia walczył o polską koronę — i w końcu ją zdobył w 1320 roku, trzydzieści lat po jej prawdopodobnej śmierci. Otaczał ją jednak pewien skandal: papiestwo mogło nigdy formalnie nie zatwierdzić małżeństwa jej syna z jego przyrodną siostrą Jadwigą.", en:"She outlived her husband and many of his sons, reaching her sixties — remarkable for the era. Her son Władysław spent decades fighting for the Polish crown and finally claimed it in 1320, some thirty years after her likely death. A shadow hung over the family: the papacy may never have formally sanctioned her son's marriage to his own half-sister Jadwiga." }},

    { id:"henryk1b", fn:"Henryk I", ln:"Brodaty", g:"M", b:"1165", d:"1238", rs:"1232", re:"1238",
      bp:"Wrocław, Śląsk", dp:"Krośnica, Polska", nat:"PL", p:[], s:["jadwiga_slaska"], image:"Matejko_Stroynowski_Papieski/henryk_i_brodaty.jpg", map:"maps/1201-1241.png",
      bio:{ pl:"Zjednoczył znaczną część ziem polskich w chwili, gdy rozbicie dzielnicowe sięgało zenitu — i zrobił to nie siłą, lecz cierpliwą polityką sojuszy. Jego najtrwalszą decyzją było małżeństwo z Jadwigą ze Śląska, która z czasem stała się świętą. Gdy Henryk umarł, jej kanonizacja była już tylko kwestią czasu.", en:"He unified a large part of Polish lands at the very height of feudal fragmentation — and did it not by force but by patient alliance-building. His most lasting decision was his marriage to Jadwiga of Silesia, who would become a saint. When Henryk died, her canonisation was only a matter of time." }},

    { id:"jadwiga_slaska", fn:"Jadwiga", ln:"Śląska", g:"F", b:"~1174", d:"1243-10-15",
      bp:"Andechs, Bawaria", dp:"Trzebnica, Polska", nat:"DE", p:[], s:["henryk1b"], image:"Matejko_Stroynowski_Papieski/sw_jadwiga.jpg",
      bio:{ pl:"Wielokrotnie składała śluby czystości — mąż Henryk musiał za każdym razem wyjeżdżać po papieską dyspensę. Chodziła boso po śniegu do ubogich, rozdawała majątek i fundowała klasztory. Gdy jej syn Henryk II zginął pod Legnicą w 1241 roku, zidentyfikowała jego ciało wśród tysięcy poległych — i powiedziała, że nie opłakuje go jak matka, lecz przyjmuje śmierć jak ofiarę Bogu. Kanonizowano ją 26 lat po śmierci.", en:"She took vows of chastity repeatedly, each time forcing her husband Henryk to travel for papal dispensation. She walked barefoot in snow to visit the poor, gave away fortunes, and founded monasteries. When her son Henryk II was killed at Legnica in 1241, she identified his body among thousands of fallen — and declared she did not mourn him as a mother, but accepted his death as a sacrifice to God. She was canonised 26 years after her death." }},

    { id:"henryk2p", fn:"Henryk II", ln:"Pobożny", g:"M", b:"1196", d:"1241", rs:"1238", re:"1241",
      bp:"Polska", dp:"Legnica, Polska", nat:"PL", p:["henryk1b","jadwiga_slaska"], s:["anna_przemyslidka"], image:null, map:"maps/1201-1241.png",
      bio:{ pl:"Umarł mając 45 lat pod Legnicą 9 kwietnia 1241 roku, prowadząc koalicję śląsko-polsko-templariuszką przeciw armii mongolskiej. Jego śmierć — i niezwykłe wycofanie się Mongołów po zwycięskiej dla nich bitwie — sprawiły, że Europa Zachodnia nigdy nie doświadczyła mongolskiej inwazji. Głowy poległych nakazano nałożyć na dzidy i obnosić wokół murów Legnicy. Jego matka Jadwiga rozpoznała ciało syna po stopie.", en:"He died at 45 at Legnica on 9 April 1241, leading a Silesian-Polish-Templar coalition against the Mongol army. His death — and the Mongols' unexpected withdrawal after their victory — meant that Western Europe never experienced a Mongol invasion. The heads of the fallen were placed on lances and carried around the walls of Legnica. His mother Jadwiga identified his body by his foot." }},

    { id:"anna_przemyslidka", fn:"Anna", ln:"Przemyślidka", g:"F", b:"1204", d:"1265-06-26",
      bp:"Czechy (Bohemia)", dp:"Wrocław, Śląsk", nat:"CZ", p:[], s:["henryk2p"], image:"Matejko_Stroynowski_Papieski/anna_przemyslidka.png",
      bio:{ pl:"Poślubiła Henryka II w 1216 roku, mając 12 lat. Przez ćwierć wieku żyła w cieniu swojej słynnej teściowej, świętej Jadwigi Śląskiej. Gdy Mongołowie zabili jej męża pod Legnicą w 1241 roku, Anna miała 37 lat — i jeszcze 24 lata życia przed sobą. Sama zarządzała śląskim dziedzictwem, doglądała wychowania dzieci i fundacji klasztornych. Jej siostrą była bł. Agnieszka Czeska, założycielka szpitala w Pradze.", en:"She married Henryk II in 1216, aged twelve. For a quarter-century she lived in the shadow of her famous mother-in-law, Saint Jadwiga of Silesia. When the Mongols killed her husband at Legnica in 1241, Anna was 37 — with 24 more years ahead of her. She managed the Silesian inheritance alone, overseeing the children's upbringing and the family's religious foundations. Her sister was Blessed Agnes of Bohemia, founder of a hospital in Prague." }},

    { id:"boleslaw5", fn:"Bolesław V", ln:"Wstydliwy", g:"M", b:"1226", d:"1279", rs:"1243", re:"1279",
      bp:"Stary Korczyn, Polska", dp:"Kraków, Polska", nat:"PL", p:["leszek1","grzymislawa"], s:["kinga_wegierska"], image:"Matejko_Stroynowski_Papieski/boleslaw_v_wstydliwy.jpg", map:"maps/1190.svg.png",
      bio:{ pl:"Trzy najazdy mongolskie — 1241, 1259, 1287 — i trzy razy Bolesław Wstydliwy ocalił Małopolskę. Żył w celibacie razem z żoną Kingą (oboje zostaną kanonizowani), doprowadził do kanonizacji biskupa Stanisława ze Szczepanowa i pod koniec panowania wyjednał Krakowowi liczne przywileje. Królestwo za jego rządów kwitło — i nie miał kto po nim dziedziczyć.", en:"Three Mongol invasions — 1241, 1259, 1287 — and three times Bolesław the Chaste saved Lesser Poland. He lived in celibacy with his wife Kinga (both would be canonised), achieved the canonisation of Bishop Stanisław of Szczepanów, and obtained numerous privileges for Kraków. The duchy flourished under his reign — and he had no heir to follow him." }},

    { id:"kinga_wegierska", fn:"Kinga", ln:"Węgierska", g:"F", b:"1224", d:"1292",
      bp:"Esztergom, Węgry", dp:"Stary Sącz, Polska", nat:"HU", p:[], s:["boleslaw5"], image:null,
      bio:{ pl:"Córka króla Węgier Béli IV. Poślubiła Bolesława Wstydliwego w 1239 roku, gdy oboje mieli kilkanaście lat — i oboje złożyli śluby czystości, stąd jego przydomek. Legenda wiąże ją z kopalnią soli w Wieliczce: wrzuciwszy pierścionek zaręczynowy do węgierskiego szybu solnego, odnalazła go podobno w Wieliczce. Przeżyła trzeci najazd mongolski na Polskę, chowając się w jaskiniach Pienin. Założyła klasztor klarysek w Starym Sączu. Kanonizowana przez Jana Pawła II w 1999 roku.", en:"Daughter of King Béla IV of Hungary. She married Bolesław the Chaste in 1239 when both were teenagers, and both took vows of celibacy — hence his epithet. Legend connects her to the Wieliczka salt mine: she threw her engagement ring into a Hungarian salt shaft and reportedly found it at Wieliczka. She survived the third Mongol invasion of Poland, sheltering in the caves of the Pieniny. She founded the Poor Clares convent at Stary Sącz. Canonised by John Paul II in 1999." }},

    { id:"leszek2", fn:"Leszek II", ln:"Czarny", g:"M", b:"1240", d:"1288", rs:"1279", re:"1288",
      bp:"Inowrocław, Polska", dp:"Kraków, Polska", nat:"PL", p:["kazimierz_i_kujawski","konstancja_wroclawska"], s:[], image:"Matejko_Stroynowski_Papieski/leszek_czarny.jpg", map:"maps/1190.svg.png",
      bio:{ pl:"Trzymał Kraków przez dziewięć lat i odpierał Litwinów, Jadźwingów i Rusinów, by go utrzymać. Leszek Czarny był ostatnim kujawskim Piastem na tronie krakowskim — po nim przejęły go juniorskie linie śląskie — i umarł bez następców. Solidny, niedoceniany władca, który trzymał Małopolskę w całości, gdy łatwo mogła się rozpaść.", en:"He held Kraków for nine years and fought off Lithuanians, Yotvingians and Ruthenians to keep it. Leszek the Black was the last of the Kuyavian Piasts on the Kraków throne — after him the junior Silesian lines took over — and he died without heirs. A competent, underrated ruler who kept Lesser Poland intact when it easily could have fallen apart." }},

    { id:"przemysl2", fn:"Przemysł II", ln:"Piast", g:"M", b:"1257", d:"1296", rs:"1295", re:"1296",
      bp:"Poznań, Polska", dp:"Rogoźno, Polska", nat:"PL", p:[], s:[], image:"Matejko_Stroynowski_Papieski/przemysl_ii.jpg", map:"maps/1275-1300.png",
      bio:{ pl:"Dziewiętnaście lat jako książę Wielkopolski, dziewięć miesięcy jako król Polski, potem śmierć. Przemysł II został koronowany w czerwcu 1295 roku — pierwszy król Polski od 219 lat — i zamordowany w lutym 1296, niemal na pewno przez agentów brandenburskich. Umarł w wieku 38 lat, osiągnąwszy to, na co pracował całe życie.", en:"Nineteen years as Duke of Greater Poland, then nine months as King of Poland, then death. Przemysł II was crowned in June 1295 — the first King of Poland in 219 years — and assassinated in February 1296, almost certainly by Brandenburg agents. He died at 38 having achieved what he spent his entire reign working toward." }},

    { id:"wladyslaw1l", fn:"Władysław I", ln:"Łokietek", g:"M", b:"1261", d:"1333", rs:"1306", re:"1333",
      bp:"Brześć Kujawski, Polska", dp:"Kraków, Polska", nat:"PL", p:["kazimierz_i_kujawski","eufrozyna_opolska"], s:["jadwiga_kuj"], image:"Matejko_Stroynowski_Papieski/wladyslaw_i_lokietek.jpg", map:"maps/1304-1333.png",
      bio:{ pl:"'Łokietek' — kpiące przezwisko małego, zadziornego księcia, po którym nikt nie spodziewał się przeżycia. Władysław spędził dziesięciolecia jako wygnaniec, dwukrotnie wygnany, walczący bez przerwy, powoli zdobywając poparcie — aż w 1320 roku stanął do koronacji w katedrze wawelskiej. Miał 59 lat. Walczył o tę chwilę, zanim większość jego dworzan przyszła na świat. W wieku 72 lat pokonał Krzyżaków pod Płowcami.", en:"'Elbow-High' — the mocking nickname for a short, scrappy duke nobody expected to survive. Władysław spent decades as a fugitive, exiled twice, fighting constantly, slowly accumulating support until in 1320 he was crowned in Wawel Cathedral. He was 59. He had been fighting for this since before most of his courtiers were born. Then at 72 he defeated the Teutonic Knights at Płowce and proved his army could hold the field." }},

    { id:"jadwiga_kuj", fn:"Jadwiga", ln:"Kujawska", g:"F", b:"1266", d:"1339",
      bp:"Kujawy, Polska", dp:"Kraków, Polska", nat:"PL", p:[], s:["wladyslaw1l"], image:null,
      bio:{ pl:"Była jego przyrodną siostrą i jego żoną — stanowisko papiestwa w tej sprawie nigdy nie było w pełni jasne. Jadwiga Kujawska przeżyła chaos długiej walki męża o koronę i przeżyła go o sześć lat, umierając w 1339 roku widząc, że jej syn Kazimierz obronił to, o co ojciec walczył. Pochowana jest w katedrze wawelskiej.", en:"She was his half-sister and his wife — the papacy's position on the matter was never entirely clear. Jadwiga of Kujawy survived the chaos of her husband's long struggle for the crown and outlived him by six years, dying in 1339 having seen her son Kazimierz secure what his father had fought for. She is buried in Wawel Cathedral." }},

    { id:"kazimierz3", fn:"Kazimierz III", ln:"Wielki", g:"M", b:"1310", d:"1370", rs:"1333", re:"1370",
      bp:"Kowal, Polska", dp:"Kraków, Polska", nat:"PL", p:["wladyslaw1l","jadwiga_kuj"], s:["aldona","adelajda"], image:"Matejko_Stroynowski_Papieski/kazimierz_iii_wielki.jpg", map:"maps/1333-1370.png", media:"video/kazimierz_wielki.mp4",
      bio:{ pl:"Znalazł Polskę drewnianą i zostawił murowaną — taki był werdykt kronik, i trafny. Kazimierz Wielki skodyfikował dwa systemy prawa w jeden, wzniósł 53 zamki i ufortyfikował 27 miast, przyjął 100 000 żydowskich uchodźców gdy Europa Zachodnia ich paliła, założył Akademię Krakowską i poczwórnie powiększył skarb. Miał też cztery żony, żadnego prawowitego syna i słabość do pięknych kobiet, która trzymała dwór w nieustannym skandalu. Był ostatnim Piastem.", en:"He found Poland built of wood and left it built of stone — the verdict of the chronicles, and accurate. Casimir the Great codified two legal systems into one, built 53 castles and fortified 27 towns, accepted 100,000 Jewish refugees when Western Europe was burning them, founded the Kraków Academy, and quadrupled his treasury. He also had four wives, no legitimate male heirs, and a weakness for beautiful women that kept his court in constant scandal. He was the last Piast." }},

    { id:"aldona", fn:"Aldona Anna", ln:"Litewska", g:"F", b:"1309", d:"1339",
      bp:"Litwa", dp:"Kraków, Polska", nat:"LT", p:[], s:["kazimierz3"], image:null,
      bio:{ pl:"Przybyła z Litwy z imieniem, którego nikt w Krakowie nie umiał wymówić, przyjęła chrzest jako Anna i umarła w wieku 30 lat po dziewięciu latach jako królowa Polski, zostawiając jedynie córki. Osobista więź między nią a Kazimierzem pozostaje nieprzenikniona — dokumenty odnotowują jej obecność, ale nie więcej. Umarła w roku, w którym Kazimierz zaczął uganiać się za innymi kobietami.", en:"She came from Lithuania bearing a name nobody in Kraków could pronounce, took the Christian name Anna at her baptism, and died at 30 after nine years as Queen of Poland, leaving only daughters. The personal bond between her and Kazimierz remains opaque — the records show her presence but little else. She died the year Kazimierz began pursuing other women." }},

    { id:"adelajda", fn:"Adelajda", ln:"Heska", g:"F", b:"1324", d:"1371",
      bp:"Hesja, Niemcy", dp:"Niemcy", nat:"DE", p:[], s:["kazimierz3"], image:null,
      bio:{ pl:"Poślubił ją z powodów dyplomatycznych i porzucił dla miłości. Adelajda Heska była drugą żoną Kazimierza, niemiecką księżniczką, która większość małżeństwa spędziła odseparowana od męża publicznie oddanego swojej metresie Estefanii Rokiczanie. Przeżyła go o rok, ale nigdy nie wróciła do Polski.", en:"He married her for diplomacy and left her for love. Adelajda of Hesse was Casimir's second wife, a German princess who spent most of her marriage separated from her husband, who was publicly devoted to his mistress Estefania Rokiczana. She outlived him by a year but never returned to Poland." }},

    // ═══════════════════════════════════════════════════════════════
    // ANJOU DYNASTY  (1370–1386)
    // ═══════════════════════════════════════════════════════════════

    { id:"ludwik1", fn:"Ludwik I", ln:"Węgierski", g:"M", b:"1326", d:"1382", rs:"1370", re:"1382",
      bp:"Visegrád, Węgry", dp:"Trnava, Słowacja", nat:"HU", p:[], s:[], image:"Matejko_Stroynowski_Papieski/ludwik_wegierski.jpg", map:"maps/1333-1370.png",
      bio:{ pl:"Odziedziczył Polskę przez matkę — była siostrą Kazimierza Wielkiego — i rządził nią przez 12 lat z Węgier, głównie przez namiestników. Węgrzy mówili o nim 'Wielki'; Polacy mieli bardziej niejednoznaczną opinię. Jego prawdziwym darem dla Polski był przywilej koszycki z 1374 roku: w zamian za przyjęcie córki jako następczyni szlachta dostała ulgi podatkowe, których miała się kurczowo trzymać przez 400 lat.", en:"He inherited Poland through his mother — she was Casimir the Great's sister — and ruled it for 12 years from Hungary, mostly through regents. He was 'the Great' to the Hungarians; the Poles found him rather more ambiguous. His real gift to Poland was the Privilege of Koszyce (1374): in exchange for accepting his daughter as successor, the nobility got tax exemptions they would cling to for 400 years." }},

    { id:"jadwiga", fn:"Jadwiga", ln:"Andegaweńska", g:"F", b:"1373", d:"1399", rs:"1384", re:"1399",
      bp:"Buda, Węgry", dp:"Kraków, Polska", nat:"PL", p:["ludwik1"], s:["wladyslaw2j"], image:"Matejko_Stroynowski_Papieski/jadwiga_andegawenska.jpg", map:"maps/jagello.png",
      bio:{ pl:"Miała jedenaście lat, gdy po raz pierwszy zaręczono ją z Wilhelmem Habsburgiem, i czternaście gdy polska szlachta oderwała ją od niego i wydała za litewskiego poganina dwa razy starszego. Sama to wybrała — źródła nalegają — albo przynajmniej przyjęła. Jej małżeństwo z Jagiełłą w 1386 roku uczłaszczyło Litwę, stworzyło unię polsko-litewską i zmieniło polityczną mapę Europy Północnej. Umarła mając 25 lat. Jan Paweł II kanonizował ją sześć wieków później.", en:"She was eleven when first betrothed to Wilhelm of Habsburg, and fourteen when the Polish nobility tore her away from him and married her to a Lithuanian pagan twice her age. She chose it herself, the sources insist — or at least accepted it. Her marriage to Jagiełło in 1386 made Lithuania Christian, created the Polish-Lithuanian union, and changed the political map of Northern Europe. She died at 25. John Paul II canonised her six centuries later." }},

    // ═══════════════════════════════════════════════════════════════
    // JAGIELLONIAN DYNASTY  (1386–1572)
    // ═══════════════════════════════════════════════════════════════

    { id:"wladyslaw2j", fn:"Władysław II", ln:"Jagiełło", g:"M", b:"1352", d:"1434", rs:"1386", re:"1434",
      bp:"Litwa", dp:"Medyka, Polska", nat:"LT", p:[], s:["jadwiga","zofia_holszanska"], image:"Matejko_Stroynowski_Papieski/wladyslaw_ii_jagiello.jpg", map:"maps/jagello.png",
      bio:{ pl:"Był pogańskim watażką, który poprzez małżeństwo stał się królem najpotężniejszego państwa Europy Północnej. Czy Władysław II naprawdę stał się chrześcijaninem, czy jedynie grał chrześcijanina — nikt nie mógł powiedzieć. Ale grał to wspaniale: odnowił Akademię Krakowską, fundował kościoły, wygrał Grunwald. Rządził Polską 48 lat, umierając w wieku 82 lub 83 lat. Założył dynastię, która trwała do 1572 roku.", en:"He was a pagan warlord who became, through marriage, the king of the most powerful state in Northern Europe. Whether Władysław II ever became truly Christian or merely performed Christianity, nobody could say — but he performed it magnificently: he renewed the Kraków Academy, endowed churches, won Grunwald. He ruled Poland for 48 years, dying at 82 or 83. He founded the dynasty that lasted until 1572." }},

    { id:"zofia_holszanska", fn:"Zofia", ln:"Holszańska", g:"F", b:"1405", d:"1461",
      bp:"Litwa", dp:"Kraków, Polska", nat:"LT", p:[], s:["wladyslaw2j"], image:null,
      bio:{ pl:"Jego czwarta żona miała 18 lat, gdy wychodziła za mąż; on — 66. Dała mu synów — Władysława i Kazimierza — których trzy poprzednie żony nie zdołały urodzić. Po jego śmierci sprawowała regencję, nawigując między frakcjami otaczającymi nastolatka z widoczną sprawnością. Dynastia, którą zabezpieczyła, rządziła Polską jeszcze 70 lat po jej śmierci.", en:"His fourth wife was 18 when he married her; he was 66. She gave him the sons — Władysław and Kazimierz — that his three previous wives hadn't. After his death she governed as regent, navigating the factions around her teenage son with evident competence. The dynasty she secured would rule Poland for another 70 years after her death." }},

    { id:"wladyslaw3", fn:"Władysław III", ln:"Warneńczyk", g:"M", b:"1424", d:"1444", rs:"1434", re:"1444",
      bp:"Kraków, Polska", dp:"Warna, Bułgaria", nat:"PL", p:["wladyslaw2j","zofia_holszanska"], s:[], image:"Matejko_Stroynowski_Papieski/wladyslaw_iii_warneczyk.jpg", map:"maps/1400.jpg",
      bio:{ pl:"Miał 20 lat i prowadził krucjatę. Władysław III zginął w Bitwie pod Warną w listopadzie 1444 roku, szarżując kawalerią na osmańskie linie w chwili wielkiej odwagi lub katastrofalnej brawury — zależnie od tego, której relacji się wierzy. Jego ciała nigdy nie odnaleziono, co przez dziesięciolecia dawało życie legendzie, że przeżył i żyje jako pustelnik na wyspie Madera.", en:"He was 20 years old and leading a crusade. Władysław III died at the Battle of Varna in November 1444, charging the Ottoman lines in a moment of either great courage or catastrophic recklessness, depending on your reading of the accounts. His body was never recovered — which for decades fed the legend that he had survived and was living as a hermit on the island of Madeira." }},

    { id:"kazimierz4", fn:"Kazimierz IV", ln:"Jagiellończyk", g:"M", b:"1427", d:"1492", rs:"1447", re:"1492",
      bp:"Kraków, Polska", dp:"Grodno, Litwa", nat:"PL", p:["wladyslaw2j","zofia_holszanska"], s:["elzbieta_hab"], image:"Matejko_Stroynowski_Papieski/kazimierz_iv_jagiellonczyk.jpg", map:"maps/1490.png",
      bio:{ pl:"'Rodzina królów.' Kazimierz IV rządził przez 45 lat, przez 13 z nich walczył z Krzyżakami i wygrał, i spłodził 13 dzieci — czworo z nich zostało królami. Jego synowie zasiadali jednocześnie na tronach Polski, Czech, Węgier i Litwy. Był dynastycznie najskuteczniejszym ze wszystkich Jagiellonów i być może najmniej osobicie dramatycznym.", en:"'The Family of Kings.' Casimir IV ruled for 45 years, fought the Teutonic Knights for 13 of them and won, and produced 13 children — four of whom became kings. His sons sat simultaneously on the thrones of Poland, Bohemia, Hungary and Lithuania. He was the most dynastically successful of all the Jagiellonians, and possibly the least personally dramatic." }},

    { id:"elzbieta_hab", fn:"Elżbieta", ln:"Habsburżanka", g:"F", b:"1436", d:"1505",
      bp:"Austria", dp:"Kraków, Polska", nat:"AT", p:[], s:["kazimierz4"], image:null,
      bio:{ pl:"Urodziła 13 dzieci, wychowała czterech królów, zarządzała dworem przez 45 lat panowania męża i przeżyła go o 13 lat. 'Matka Królów' był jej tytuł i mówi wszystko o tym, jak współcześni rozumieli jej rolę. Umarła mając 69 lat, widząc jak ustanawiano więcej tronów królewskich niż większość dynastii osiąga w ciągu stulecia.", en:"She bore 13 children, raised four kings, managed the court through 45 years of her husband's reign, and outlived him by 13 years. 'Mother of Kings' was her title and it tells everything about how her contemporaries understood her role. She was 69 when she died, having seen more royal courts established than most dynasties manage in a century." }},

    { id:"jan1", fn:"Jan I", ln:"Olbracht", g:"M", b:"1459", d:"1501", rs:"1492", re:"1501",
      bp:"Kraków, Polska", dp:"Toruń, Polska", nat:"PL", p:["kazimierz4","elzbieta_hab"], s:[], image:"Matejko_Stroynowski_Papieski/jan_i_olbracht.jpg", map:"maps/1490.png",
      bio:{ pl:"Kampania mołdawska w 1497 roku była katastrofą definiującą. Jan I Olbracht poprowadził armię w bukowińskie lasy i Mołdawianie urządzili zasadzkę — szlachta ginęła tysiącami, a powiedzonko 'Za króla Olbrachta wyginęła szlachta' ścigało go aż do grobu. Umarł dziewięć lat później w wieku 42 lat, bez następców.", en:"The Moldavian campaign of 1497 was the defining catastrophe. Jan I Olbracht led his army into the Bukovina forests and the Moldavians ambushed them — the szlachta was slaughtered by the thousands, and the proverb 'Under Olbracht the nobility perished' followed him to his grave. He died nine years later at 42, without heirs." }},

    { id:"aleksander1", fn:"Aleksander I", ln:"Jagiellończyk", g:"M", b:"1461", d:"1506", rs:"1501", re:"1506",
      bp:"Kraków, Polska", dp:"Wilno, Litwa", nat:"PL", p:["kazimierz4","elzbieta_hab"], s:[], image:"Matejko_Stroynowski_Papieski/aleksander_jagiellonczyk.jpg", map:"maps/1490.png",
      bio:{ pl:"Dał szlachcie coś, czego ta nigdy nie oddała. Przywilej Nihil Novi z 1505 roku — 'nic nowego' bez zgody sejmu — wydawał się w swoim czasie rozsądną koncesją. W następnym stuleciu szlachta użyje tej zasady do całkowitego sparaliżowania państwa. Aleksander umarł pięć lat później w wieku 45 lat, być może nigdy nie rozumiejąc, co oddał.", en:"He gave the nobility something they would never give back. The Nihil Novi privilege of 1505 — nothing new without parliamentary consent — seemed like a reasonable concession at the time. By the following century, the nobility would use this principle to paralyse the state completely. Aleksander died five years later at 45, possibly never understanding what he had handed away." }},

    { id:"zygmunt1", fn:"Zygmunt I", ln:"Stary", g:"M", b:"1467", d:"1548", rs:"1506", re:"1548",
      bp:"Kozienice, Polska", dp:"Kraków, Polska", nat:"PL", p:["kazimierz4","elzbieta_hab"], s:["barbara_zapolya","bona_sforza"], image:"Matejko_Stroynowski_Papieski/zygmunt_i_stary.jpg", map:"maps/1561.png",
      bio:{ pl:"Sześćdziesiąt lat, dwie żony, renesans w Polsce. Zygmunt Stary był ostatnim wielkim średniowiecznym i pierwszym renesansowym królem polskim — bił Zakon Krzyżacki, bił Moskwę, bił Habsburgów i przewodniczył najświetniejszemu kulturalnie dworowi w Europie Środkowej. Jego druga żona Bona sprowadziła włoskich architektów, kucharzy i ogrodników. Umarł mając 81 lat — czego przed nim ani po nim nikomu nie udało się osiągnąć.", en:"Sixty years, two wives, the Renaissance in Poland. Sigismund the Old was the last great medieval Polish king and the first Renaissance one — he fought the Teutonic Order into submission, fought Muscovy, fought the Habsburgs, and presided over the most culturally brilliant court in Central Europe. His second wife Bona imported Italian architects, cooks and gardeners. He died at 81 — which nobody managed before or after." }},

    { id:"barbara_zapolya", fn:"Barbara", ln:"Zápolya", g:"F", b:"1495", d:"1515",
      bp:"Węgry", dp:"Kraków, Polska", nat:"HU", p:[], s:["zygmunt1"], image:null,
      bio:{ pl:"Umarła w wieku 20 lat, dwa lata po ślubie, który miał przypieczętować sojusz węgiersko-polski. Żadnych dzieci, żadnego wpływu, ledwie ślad w historycznym zapisie — panna młoda, która przyjechała do Krakowa i nie przeżyła wystarczająco długo, by stać się królową w jakimkolwiek znaczącym sensie.", en:"She died at 20, two years after the marriage meant to seal the Hungarian-Polish alliance. No children, no influence, barely a trace in the historical record — a bride who came to Kraków and didn't survive long enough to become queen in any meaningful sense." }},

    { id:"bona_sforza", fn:"Bona", ln:"Sforza", g:"F", b:"1494", d:"1557",
      bp:"Vigevano, Włochy", dp:"Bari, Włochy", nat:"IT", p:[], s:["zygmunt1"], image:null,
      bio:{ pl:"Przybyła z Mediolanu z własną agendą i realizowała ją przez 40 lat. Bona Sforza zrewolucjonizowała polski dwór — włoska architektura, włoska kuchnia, włoski design ogrodów (przypisuje się jej wprowadzenie do Polski warzyw, które Polacy uważają dziś za własne). Przez 40 lat manewrowała też w polityce dworskiej, oskarżana o otrucie synowej Barbary Radziwiłłówny, po czym wycofała się do Bari z majątkiem. 'Królowa-pająk' umarła tam w 1557 roku — być może sama otruta.", en:"She arrived from Milan with her own agenda and pursued it for 40 years. Bona Sforza transformed the Polish court — Italian architecture, Italian cuisine, Italian garden design (she is credited with bringing vegetables to Poland that Poles now consider their own). She also spent 40 years manoeuvring in court politics, accused of poisoning her daughter-in-law Barbara Radziwiłł, before withdrawing to Bari with her fortune. The 'Spider Queen' died there in 1557, possibly poisoned herself." }},

    { id:"zygmunt2", fn:"Zygmunt II", ln:"August", g:"M", b:"1520", d:"1572", rs:"1548", re:"1572",
      bp:"Kraków, Polska", dp:"Knyszyn, Polska", nat:"PL", p:["zygmunt1","bona_sforza"], s:["barbara_radziwill"], image:"Matejko_Stroynowski_Papieski/zygmunt_ii_august.jpg", map:"maps/1561.png",
      bio:{ pl:"Ożenił się z Barbarą Radziwiłłówną wbrew woli matki, wbrew wyraźnej woli sejmu, wbrew wszelkiej politycznej kalkulacji epoki — z czystej miłości. Umarła rok po koronacji. Spędził pozostałe 21 lat panowania budując Unię Lubelską i zbierając dzieła sztuki, żonaty z kobietami, których nie chciał. Umarł w 1572 roku bez prawowitych następców, kończąc dynastię Jagiellonów.", en:"He married Barbara Radziwiłł against his mother's explicit wishes, against the Sejm's explicit wishes, against every political calculation of the age — purely for love. She died a year after her coronation. He spent the remaining 21 years of his reign building the Union of Lublin and collecting art, all while married to women he didn't want. He died in 1572 without legitimate heirs, ending the Jagiellonian dynasty." }},

    { id:"barbara_radziwill", fn:"Barbara", ln:"Radziwiłłówna", g:"F", b:"1520", d:"1551",
      bp:"Wilno, Litwa", dp:"Kraków, Polska", nat:"LT", p:[], s:["zygmunt2"], image:null,
      bio:{ pl:"Najsławniejsza polska historia miłosna — i jedna z najbardziej podejrzanych śmierci. Barbara Radziwiłłówna była litewską wdową, gdy Zygmunt się w niej zakochał — poniżej jego stanu, w opozycji matki, w opozycji sejmu. Ożenił się z nią potajemnie, potem stoczył parlamentarną bitwę o jej koronację. Koronowano ją w 1550 roku. Rok później umarła w wieku 30 lat, na chorobę, której lekarze nie umieli nazwać. Bona Sforza była powszechnie podejrzewana o otrucie. Czy to prawda czy nie — wszyscy w to wierzyli.", en:"The most famous Polish love story — and one of its most suspicious deaths. Barbara Radziwiłł was a Lithuanian widow when Sigismund fell for her — below his station, opposed by his mother, opposed by the Sejm. He married her secretly, then fought a parliamentary battle to have her crowned. She was crowned in 1550. She died in 1551 at 30, of an illness her doctors couldn't name. Bona Sforza was widely suspected of poisoning her. Whether or not that was true, everyone believed it." }},

    // ═══════════════════════════════════════════════════════════════
    // ELECTED KINGS  (1573–1795)
    // ═══════════════════════════════════════════════════════════════

    { id:"henryk_walois", fn:"Henryk III", ln:"Walezjusz", g:"M", b:"1551", d:"1589", rs:"1573", re:"1574",
      bp:"Fontainebleau, Francja", dp:"Saint-Cloud, Francja", nat:"FR", p:[], s:[], image:"Matejko_Stroynowski_Papieski/henryk_iii_walezy.jpg", map:"maps/1561.png",
      bio:{ pl:"Przybył do Krakowa z francuskimi dworzanami, którzy skandalizowali Polaków swoimi perfumami i manierami. Henryk Walezjusz panował jako król Polski przez mniej niż rok, zanim jego brat Karol IX umarł we Francji. Nie czekał na pozwolenie wyjazdu — wyślizgnął się z zamku wawelskiego pewnej nocy w czerwcu 1574, cwałował do granicy i nigdy nie wrócił. Potem jako Henryk III Francji zginął od sztyletów zamachowca w 1589 roku.", en:"He arrived in Kraków with French courtiers who scandalized the Poles with their perfume and manners. Henryk Valois reigned as King of Poland for less than a year before his brother Charles IX died in France. He didn't wait for permission to leave — he slipped out of Wawel Castle one night in June 1574, rode hard for the border, and never came back. Later as Henri III of France, he died by an assassin's blade in 1589." }},

    { id:"anna_jag", fn:"Anna", ln:"Jagiellonka", g:"F", b:"1523", d:"1596", rs:"1575", re:"1596",
      bp:"Kraków, Polska", dp:"Warszawa, Polska", nat:"PL", p:["zygmunt1","bona_sforza"], s:["stefan_batory"], image:"Matejko_Stroynowski_Papieski/anna_jagiellonka.jpg", map:"maps/1561.png",
      bio:{ pl:"Miała 52 lata, gdy została królową Polski. Anna Jagiellonka — ostatnia z dynastii — czekała trzy dziesięciolecia w tle, podczas gdy jej brat Zygmunt II August rządził i umarł bez następców. Szlachta potrzebowała jagiellońskiej legitymizacji; ona ją zapewniła, wychodząc za Stefana Batorego jako warunek jego elekcji. Przeżyła go o dziesięć lat i umarła w 1596 roku — ostatnia żywa nić jagiellońskiej linii.", en:"She was 52 when she became Queen of Poland. Anna Jagiellon — last of her dynasty — had waited three decades in the background while her brother Sigismund II Augustus ruled and died without heirs. The nobility needed Jagiellonian legitimacy; she provided it, marrying Stefan Báthory as a condition of his election. She outlived him by ten years and died in 1596, the last living thread of the Jagiellonian line." }},

    { id:"stefan_batory", fn:"Stefan", ln:"Batory", g:"M", b:"1533", d:"1586", rs:"1576", re:"1586",
      bp:"Szilágysomlyó, Węgry", dp:"Grodno, Litwa", nat:"HU", p:[], s:["anna_jag"], image:"Matejko_Stroynowski_Papieski/stefan_batory.jpg", map:"maps/1600.png",
      bio:{ pl:"Trzy lata kampanii przeciw Iwanowi Groźnemu — i Iwan był złamany. Stefan Batory przybył do Polski jako kompromisowy kandydat i stał się jednym z największych wodzów, jakich kraj kiedykolwiek miał: odbił Połock, oblegał Psków, zreformował armię węgierskimi i niemieckimi innowacjami i zmusił cara Moskwy do negocjacji. Umarł w wieku 53 lat, prawdopodobnie na niewydolność nerek, zostawiając kampanie, których nie zdołał dokończyć.", en:"Three years of campaigns against Ivan the Terrible — and Ivan was broken. Stefan Báthory arrived in Poland as a compromise candidate and became one of the greatest military commanders the country ever had: he retook Polotsk, besieged Pskov, reformed the army with Hungarian and German innovations, and forced the Tsar of Moscow to negotiate. He died at 53, probably of kidney failure, leaving campaigns unfinished." }},

    { id:"zygmunt3", fn:"Zygmunt III", ln:"Waza", g:"M", b:"1566", d:"1632", rs:"1587", re:"1632",
      bp:"Gripsholm, Szwecja", dp:"Warszawa, Polska", nat:"SE", p:[], s:["anna_hab","konstancja_hab"], image:"Matejko_Stroynowski_Papieski/zygmunt_iii_waza.jpg", map:"maps/1600.png",
      bio:{ pl:"Stracił szwedzki tron za nadmierny katolicyzm, utrzymał polski tron przeżywając wszystkich i przeniósł stolicę do Warszawy z czystego uporu. Zygmunt III Waza panował przez 45 lat — najdłużej spośród wszystkich królów elekcyjnych — i większość tego czasu spędził na wojnie: ze Szwecją o roszczenia dynastyczne, z Rosją podczas Wielkiej Smuty (jego wojska zajęły Moskwę), z Turkami na południu. Pobożny, uparty, ogromnie ważny, powszechnie nielubiany.", en:"He lost the Swedish throne by being too Catholic, kept the Polish throne by outlasting everyone, and moved the capital to Warsaw out of sheer stubbornness. Sigismund III Vasa reigned for 45 years — the longest of any elected king — and spent most of it at war: with Sweden over his dynastic claim, with Russia during the Time of Troubles (his troops occupied Moscow), with the Ottomans in the south. Pious, obstinate, vastly consequential, widely disliked." }},

    { id:"anna_hab", fn:"Anna", ln:"Habsburżanka", g:"F", b:"1573", d:"1598",
      bp:"Graz, Austria", dp:"Warszawa, Polska", nat:"AT", p:[], s:["zygmunt3"], image:null,
      bio:{ pl:"Umarła w wieku 25 lat, cztery lata po ślubie, który miał związać Habsburgów z Wazami. Przed śmiercią w połogu zdążyła urodzić Władysława IV — pierwszą z serii dzieci, które Zygmunt III spłodził w dwóch niezwykle podobnych małżeństwach z habsburskimi siostrami.", en:"She died at 25, four years after the marriage meant to bind the Habsburgs to the Vasas. She bore Władysław IV before dying in childbirth — the first of what would be Sigismund III's remarkably similar two marriages to Habsburg sisters." }},

    { id:"konstancja_hab", fn:"Konstancja", ln:"Habsburżanka", g:"F", b:"1588", d:"1631",
      bp:"Graz, Austria", dp:"Warszawa, Polska", nat:"AT", p:[], s:["zygmunt3"], image:null,
      bio:{ pl:"Była zastępstwem dla siostry — dosłownie: Zygmunt III poślubił Konstancję dwa lata po śmierci Anny, z tej samej rodziny, z tą samą polityczną kalkulacją. Dała mu jeszcze sześcioro dzieci, w tym Jana II Kazimierza, i przeżyła męża o jeden rok.", en:"She was her sister's replacement — literally: Sigismund III married Konstancja two years after Anna's death, from the same family, with the same political calculation. She gave him six more children including Jan II Kazimierz, and outlived her husband by one year." }},

    { id:"wladyslaw4", fn:"Władysław IV", ln:"Waza", g:"M", b:"1595", d:"1648", rs:"1632", re:"1648",
      bp:"Łobzów, Polska", dp:"Merecz, Litwa", nat:"PL", p:["zygmunt3","anna_hab"], s:[], image:"Matejko_Stroynowski_Papieski/wladyslaw_iv_waza.jpg", map:"maps/1600.png",
      bio:{ pl:"Pokonał Rosję, pokonał Szwecję — i resztę panowania spędził próbując zacząć wojnę z Turkami, blokowany przez sejm za każdym razem. Władysław IV był ostatnim wielkim wojskowym Wazą — kompetentnym, charyzmatycznym, naprawdę popularnym — ale parlamentarny paraliż, który zniszczy Polskę, już się zacieśniał. Umarł w 1648 roku, gdy kozacka rebelia, którą przez przypadek sprowokował, właśnie rozkręcała Potop.", en:"He defeated Russia, defeated Sweden, and spent the rest of his reign trying to start a war with the Ottomans and being blocked by the Sejm every time. Władysław IV was the last great military Vasa — competent, charismatic, genuinely popular — but the parliamentary paralysis that would destroy Poland was already tightening. He died in 1648 just as the Cossack revolt he had accidentally provoked was unleashing the Deluge." }},

    { id:"jan2", fn:"Jan II Kazimierz", ln:"Waza", g:"M", b:"1609", d:"1672", rs:"1648", re:"1668",
      bp:"Kraków, Polska", dp:"Nevers, Francja", nat:"PL", p:["zygmunt3","konstancja_hab"], s:["maria_ludwika"], image:"Matejko_Stroynowski_Papieski/jan_ii_kazimierz_waza.jpg", map:"maps/1569-1795.jpg",
      bio:{ pl:"Jego panowanie było najgorszym ciągłym kryzysem w polskiej historii do tamtego momentu. Potop — jednoczesne najazdy szwedzkie, kozackie, rosyjskie, brandenburskie i siedmiogrodzkie — zredukował Polskę do niemal całkowitej okupacji między 1655 a 1660 rokiem. Jan II Kazimierz przeżył, odzyskał większość utraconych terytoriów, ale wyszedł z doświadczenia przekonany, że konstytucyjny system Polski jest zepsuty. Abdykował w 1668 roku jako pierwszy dobrowolnie, i ostatnie lata spędził jako francuski opat.", en:"His reign was the worst continuous crisis in Polish history up to that point. The Deluge — simultaneous Swedish, Cossack, Russian, Brandenburgian and Transylvanian invasions — reduced Poland to near-total occupation between 1655 and 1660. Jan II Kazimierz survived it, reconquered most of the lost territories, but emerged convinced that Poland's constitutional system was broken. He abdicated in 1668, the first Polish king to do so voluntarily, and spent his last years as a French abbot." }},

    { id:"maria_ludwika", fn:"Maria Ludwika", ln:"Gonzaga", g:"F", b:"1611", d:"1667",
      bp:"Nevers, Francja", dp:"Warszawa, Polska", nat:"FR", p:[], s:["jan2"], image:null,
      bio:{ pl:"Francuska księżniczka, która prowadziła polską politykę zagraniczną z królewskich apartamentów. Maria Ludwika Gonzaga była politycznie zdolniejsza od swojego męża i wszyscy w Warszawie o tym wiedzieli — zarządzała francuskimi interesami w Polsce, promowała kandydatów do tronu i forsowała projekt elekcji vivente rege, który uczyniłby monarchię dziedziczną. W tym ostatnim zawiodła, ale w niemal wszystkim innym osiągnęła swoje.", en:"A French princess who ran Polish foreign policy from the queen's apartments. Maria Ludwika Gonzaga was more politically capable than her husband, and everyone in Warsaw knew it — she managed French interests in Poland, promoted candidates for the throne, and pushed the vivente rege election project that would have made the monarchy hereditary. She failed in that, but succeeded in almost everything else." }},

    { id:"michal_wisnow", fn:"Michał Korybut", ln:"Wiśniowiecki", g:"M", b:"1640", d:"1673", rs:"1669", re:"1673",
      bp:"Biała, Polska", dp:"Lwów, Polska", nat:"PL", p:[], s:[], image:"Matejko_Stroynowski_Papieski/michal_korybut_wisnowiecki.jpg", map:"maps/1569-1795.jpg",
      bio:{ pl:"Wybrano go właśnie dlatego, że nie był niczyjm kandydatem — nie francuskim, nie szwedzkim, nie habsburskim. 'Piast' jakiego średnia szlachta zawsze marzyła: rdzenny Polak, ze starej rodziny, nikomu niezobowiązany. Okazał się niezdolny do zarządzania magnackimi frakcjami, które natychmiast pochłonęły jego panowanie, a traktat buczacki z 1672 roku — oddający Podole Turkom — był koronną katastrofą. Umarł mając 33 lata, być może miłosiernie.", en:"He was elected precisely because he was nobody's candidate — not French, not Swedish, not Habsburg. The 'Piast king' the middle gentry had always dreamed of: a native Pole, from an old family, beholden to no foreign power. He proved incapable of managing the magnate factions that immediately consumed his reign, and the Treaty of Buchach (1672) — surrendering Podolia to the Ottomans — was the crowning disaster. He died at 33, perhaps mercifully." }},

    { id:"jan3_sobieski", fn:"Jan III", ln:"Sobieski", g:"M", b:"1629", d:"1696", rs:"1674", re:"1696",
      bp:"Olesko, Polska", dp:"Wilanów, Polska", nat:"PL", p:[], s:["maria_kazimiera"], image:"Matejko_Stroynowski_Papieski/jan_iii_sobieski.jpg", map:"maps/1569-1795.jpg",
      bio:{ pl:"Dotarł pod Wiedeń z 27 000 ludzi i przeprowadził największą szarżę kawaleryjską w historii wojen. 12 września 1683 roku Jan Sobieski poprowadził armię odsieczną ze wzgórza Kahlenberg i rozbił osmańskie oblężenie, które dusiło Wiedeń od dwóch miesięcy — największe wojsko osmańskie kiedykolwiek wysłane do Europy. Miał 54 lata. Umarł 13 lat później, wciąż jako król, wciąż walcząc na południowych granicach, podczas gdy polskie państwo osuwało się już ku paraliżowi.", en:"He arrived at Vienna with 27,000 men and the largest cavalry charge in the history of warfare. On 12 September 1683, Jan Sobieski led the relief army down from the Kahlenberg and broke the Ottoman siege that had been strangling Vienna for two months — the largest Ottoman force ever deployed in Europe. He was 54. He died 13 years later, still king, still fighting on the southern borders, as the Polish state slid toward the paralysis that would destroy it." }},

    { id:"maria_kazimiera", fn:"Maria Kazimiera", ln:"d'Arquien", g:"F", b:"1641", d:"1716",
      bp:"Nevers, Francja", dp:"Blois, Francja", nat:"FR", p:[], s:["jan3_sobieski"], image:null,
      bio:{ pl:"'Marysieńka' — prywatne imię, którym Jan Sobieski zwracał się do niej w setkach miłosnych listów pisanych z kampanii. Maria Kazimiera d'Arquien zarządzała polityczną karierą króla z tą samą pasją, z jaką on opiekował się jej sercem — ona była strategiem, on żołnierzem. Przeżyła go o 20 lat, umarła w Rzymie, pochowana jest w Warszawie.", en:"'Marysieńka' was the private name Jan Sobieski used for her in the hundreds of love letters he wrote from campaigns. Maria Kazimiera d'Arquien managed the king's political career with the same passion he managed her heart — she was the strategist, he was the soldier. She outlived him by 20 years, died in Rome, and is buried in Warsaw." }},

    { id:"august2", fn:"August II", ln:"Mocny", g:"M", b:"1670", d:"1733", rs:"1697", re:"1733",
      bp:"Drezno, Saksonia", dp:"Warszawa, Polska", nat:"DE", p:[], s:[], image:"Matejko_Stroynowski_Papieski/august_ii_mocny.jpg", map:"maps/1569-1795.jpg",
      bio:{ pl:"Mógł gołymi rękami zgiąć podkowę i podobno spłodził 365 dzieci. Fryderyk August I Saski przeszedł na katolicyzm, by zdobyć polską koronę, po czym większość panowania albo przegrywał wojny, albo urządzał przyjęcia w drezdeńskim dworze. Jego prawdziwym osiągnięciem była wytwórnia porcelany miśnieńskiej — przetrwała wszystko inne.", en:"He could bend a horseshoe with his bare hands and reportedly fathered 365 children. Friedrich August of Saxony converted to Catholicism to get the Polish crown, then spent most of his reign either losing wars or throwing lavish parties at his Dresden court. The Meissen porcelain manufactory was his real achievement: it outlasted everything else." }},

    { id:"stanislaw_lesz", fn:"Stanisław I", ln:"Leszczyński", g:"M", b:"1677", d:"1766", rs:"1704", re:"1736",
      bp:"Lwów, Polska", dp:"Lunéville, Francja", nat:"PL", p:[], s:["katarzyna_opal"], image:"Matejko_Stroynowski_Papieski/stanislaw_leszczynski.jpg", map:"maps/1569-1795.jpg",
      bio:{ pl:"Był królem dwa razy i dwa razy stracił tron — a za drugim razem okazało się to darem. Stanisław Leszczyński spędził dziesięciolecia na wygnaniu, zanim jego córka Maria wyszła za Ludwika XV Francji, co uczyniło go z łaski francuskiej księciem Lotaryngii. Rządził nią jako oświecony filzof-książę — wzniósł wspaniały plac w Nancy noszący jego imię — i jest dziś pamiętany jako Francuz. Umarł mając 88 lat.", en:"He was king twice and lost the throne twice — and the second time turned out to be a gift. Stanisław Leszczyński spent decades in exile before his daughter Marie married Louis XV of France, making him Duke of Lorraine by French courtesy. He ruled Lorraine as an enlightened philosophe-prince, built the magnificent square in Nancy that bears his name, and is now remembered as a Frenchman. He died at 88." }},

    { id:"katarzyna_opal", fn:"Katarzyna", ln:"Opalińska", g:"F", b:"1680", d:"1747",
      bp:"Polska", dp:"Lunéville, Francja", nat:"PL", p:[], s:["stanislaw_lesz"], image:null,
      bio:{ pl:"Wyszła za Leszczyńskiego przed pierwszą koroną, przeżyła oba jego detronizacje, pojechała za nim na wygnanie do Francji i umarła w Lunéville przeżywszy wszelkie oczekiwania, jakie niosło życie u boku króla-bez-tronu. Jej córka została królową Francji. To był wynik, którego nikt nie planował.", en:"She married Leszczyński before the first crown, survived both his dethroning's, followed him into exile in France, and died in Lunéville having outlived every expectation that life beside a king-without-a-throne held. Her daughter became Queen of France. That was the outcome nobody had planned for." }},

    { id:"august3", fn:"August III", ln:"Sas", g:"M", b:"1696", d:"1763", rs:"1733", re:"1763",
      bp:"Drezno, Saksonia", dp:"Drezno, Saksonia", nat:"DE", p:["august2"], s:[], image:"Matejko_Stroynowski_Papieski/august_iii_sas.jpg", map:"maps/1569-1795.jpg",
      bio:{ pl:"Był królem przez 30 lat i może trzy z nich spędził faktycznie w Polsce. August III rządził Rzeczpospolitą z Drezna przez ministrów i faworytów, podczas gdy magnackie frakcje — Czartoryscy, Potoccy, Radziwiłłowie — prowadziły kraj między sobą. Sejm był sparaliżowany liberum veto; prawo nie powstawało. 'Saska noc' — tak historycy nazwali jego panowanie, i ta nazwa się przyjęła.", en:"He was king for 30 years and spent perhaps three of them actually in Poland. August III governed the Commonwealth from Dresden through ministers and favourites, while the magnate factions — the Czartoryskis, Potockis, Radziwiłłs — ran the country among themselves. The Sejm was paralysed by the liberum veto; legislation was nearly impossible. The 'Saxon Night' was the name historians gave his reign, and it stuck." }},

    { id:"stanislaw_aug", fn:"Stanisław August", ln:"Poniatowski", g:"M", b:"1732", d:"1798", rs:"1764", re:"1795",
      bp:"Wołczyn, Polska", dp:"Sankt Petersburg, Rosja", nat:"PL", p:[], s:[], image:"Matejko_Stroynowski_Papieski/stanislaw_august_poniatowski.jpg", map:"maps/commonwealth-borders.png",
      bio:{ pl:"Napisał Konstytucję 3 Maja 1791 roku — pierwszą nowoczesną konstytucję w Europie, dwa lata przed francuską — i patrzył, jak osiemnaście miesięcy później niszczy ją rosyjska interwencja. Stanisław August Poniatowski był dawnym kochankiem Katarzyny Wielkiej i jej wybranym instrumentem kontroli nad Polską; zaskoczył ją stając się prawdziwym reformatorem. To nie wystarczyło. Abdykował w 1795 roku, gdy III rozbiór wymazał Polskę z mapy. Umarł w Petersburgu w 1798 roku, więzień rosyjskiej gościnności.", en:"He wrote the Constitution of 3 May 1791 — the first modern constitution in Europe, two years before the French one — and watched it destroyed by Russian intervention eighteen months later. Stanisław August Poniatowski was Catherine the Great's former lover and her chosen instrument for controlling Poland; he surprised her by becoming a genuine reformer. It wasn't enough. He abdicated in 1795 as the Third Partition erased Poland from the map. He died in St. Petersburg in 1798, a prisoner of Russian hospitality." }},

  ]
};
